// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.encryptedmedia

import org.w3c.dom.encryptedmedia.MediaKeySystemConfiguration
import org.w3c.dom.encryptedmedia.MediaKeys

public actual typealias MediaKeySystemConfiguration = MediaKeySystemConfiguration

public actual typealias MediaKeys = MediaKeys
