// Generated by the kotlinx-browser common subset generator. Do not edit.
@file:Suppress("EXPECT_ACTUAL_INCOMPATIBLE_CLASS_SCOPE")

package kotlinx.browser.dom.clipboard

import kotlin.Boolean
import kotlin.Suppress
import kotlinx.browser.dom.DataTransfer

public actual typealias ClipboardEventInit = org.w3c.dom.clipboard.ClipboardEventInit

public actual typealias ClipboardPermissionDescriptor = org.w3c.dom.clipboard.ClipboardPermissionDescriptor

public actual fun ClipboardEventInit(
  clipboardData: DataTransfer?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): ClipboardEventInit = org.w3c.dom.clipboard.ClipboardEventInit(clipboardData = clipboardData, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun ClipboardPermissionDescriptor(allowWithoutGesture: Boolean?): ClipboardPermissionDescriptor = org.w3c.dom.clipboard.ClipboardPermissionDescriptor(allowWithoutGesture = allowWithoutGesture)
