// Generated by the kotlinx-browser common subset generator. Do not edit.
@file:Suppress("EXPECT_ACTUAL_INCOMPATIBLE_CLASS_SCOPE")

package kotlinx.browser.dom.events

import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlinx.browser.dom.Window

public actual typealias UIEventInit = org.w3c.dom.events.UIEventInit

public actual typealias EventModifierInit = org.w3c.dom.events.EventModifierInit

public actual typealias MouseEventInit = org.w3c.dom.events.MouseEventInit

public actual typealias CompositionEventInit = org.w3c.dom.events.CompositionEventInit

public actual typealias FocusEventInit = org.w3c.dom.events.FocusEventInit

public actual typealias InputEventInit = org.w3c.dom.events.InputEventInit

public actual typealias KeyboardEventInit = org.w3c.dom.events.KeyboardEventInit

public actual typealias WheelEventInit = org.w3c.dom.events.WheelEventInit

public actual fun UIEventInit(
  view: Window?,
  detail: Int?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): UIEventInit = org.w3c.dom.events.UIEventInit(view = view, detail = detail, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun EventModifierInit(
  ctrlKey: Boolean?,
  shiftKey: Boolean?,
  altKey: Boolean?,
  metaKey: Boolean?,
  modifierAltGraph: Boolean?,
  modifierCapsLock: Boolean?,
  modifierFn: Boolean?,
  modifierFnLock: Boolean?,
  modifierHyper: Boolean?,
  modifierNumLock: Boolean?,
  modifierScrollLock: Boolean?,
  modifierSuper: Boolean?,
  modifierSymbol: Boolean?,
  modifierSymbolLock: Boolean?,
  view: Window?,
  detail: Int?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): EventModifierInit = org.w3c.dom.events.EventModifierInit(ctrlKey = ctrlKey, shiftKey = shiftKey, altKey = altKey, metaKey = metaKey, modifierAltGraph = modifierAltGraph, modifierCapsLock = modifierCapsLock, modifierFn = modifierFn, modifierFnLock = modifierFnLock, modifierHyper = modifierHyper, modifierNumLock = modifierNumLock, modifierScrollLock = modifierScrollLock, modifierSuper = modifierSuper, modifierSymbol = modifierSymbol, modifierSymbolLock = modifierSymbolLock, view = view, detail = detail, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun MouseEventInit(
  screenX: Int?,
  screenY: Int?,
  clientX: Int?,
  clientY: Int?,
  button: Short?,
  buttons: Short?,
  relatedTarget: EventTarget?,
  region: String?,
  ctrlKey: Boolean?,
  shiftKey: Boolean?,
  altKey: Boolean?,
  metaKey: Boolean?,
  modifierAltGraph: Boolean?,
  modifierCapsLock: Boolean?,
  modifierFn: Boolean?,
  modifierFnLock: Boolean?,
  modifierHyper: Boolean?,
  modifierNumLock: Boolean?,
  modifierScrollLock: Boolean?,
  modifierSuper: Boolean?,
  modifierSymbol: Boolean?,
  modifierSymbolLock: Boolean?,
  view: Window?,
  detail: Int?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): MouseEventInit = org.w3c.dom.events.MouseEventInit(screenX = screenX, screenY = screenY, clientX = clientX, clientY = clientY, button = button, buttons = buttons, relatedTarget = relatedTarget, region = region, ctrlKey = ctrlKey, shiftKey = shiftKey, altKey = altKey, metaKey = metaKey, modifierAltGraph = modifierAltGraph, modifierCapsLock = modifierCapsLock, modifierFn = modifierFn, modifierFnLock = modifierFnLock, modifierHyper = modifierHyper, modifierNumLock = modifierNumLock, modifierScrollLock = modifierScrollLock, modifierSuper = modifierSuper, modifierSymbol = modifierSymbol, modifierSymbolLock = modifierSymbolLock, view = view, detail = detail, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun CompositionEventInit(
  `data`: String?,
  view: Window?,
  detail: Int?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): CompositionEventInit = org.w3c.dom.events.CompositionEventInit(data = data, view = view, detail = detail, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun FocusEventInit(
  relatedTarget: EventTarget?,
  view: Window?,
  detail: Int?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): FocusEventInit = org.w3c.dom.events.FocusEventInit(relatedTarget = relatedTarget, view = view, detail = detail, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun InputEventInit(
  `data`: String?,
  isComposing: Boolean?,
  view: Window?,
  detail: Int?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): InputEventInit = org.w3c.dom.events.InputEventInit(data = data, isComposing = isComposing, view = view, detail = detail, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun KeyboardEventInit(
  key: String?,
  code: String?,
  location: Int?,
  repeat: Boolean?,
  isComposing: Boolean?,
  ctrlKey: Boolean?,
  shiftKey: Boolean?,
  altKey: Boolean?,
  metaKey: Boolean?,
  modifierAltGraph: Boolean?,
  modifierCapsLock: Boolean?,
  modifierFn: Boolean?,
  modifierFnLock: Boolean?,
  modifierHyper: Boolean?,
  modifierNumLock: Boolean?,
  modifierScrollLock: Boolean?,
  modifierSuper: Boolean?,
  modifierSymbol: Boolean?,
  modifierSymbolLock: Boolean?,
  view: Window?,
  detail: Int?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): KeyboardEventInit = org.w3c.dom.events.KeyboardEventInit(key = key, code = code, location = location, repeat = repeat, isComposing = isComposing, ctrlKey = ctrlKey, shiftKey = shiftKey, altKey = altKey, metaKey = metaKey, modifierAltGraph = modifierAltGraph, modifierCapsLock = modifierCapsLock, modifierFn = modifierFn, modifierFnLock = modifierFnLock, modifierHyper = modifierHyper, modifierNumLock = modifierNumLock, modifierScrollLock = modifierScrollLock, modifierSuper = modifierSuper, modifierSymbol = modifierSymbol, modifierSymbolLock = modifierSymbolLock, view = view, detail = detail, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun WheelEventInit(
  deltaX: Double?,
  deltaY: Double?,
  deltaZ: Double?,
  deltaMode: Int?,
  screenX: Int?,
  screenY: Int?,
  clientX: Int?,
  clientY: Int?,
  button: Short?,
  buttons: Short?,
  relatedTarget: EventTarget?,
  region: String?,
  ctrlKey: Boolean?,
  shiftKey: Boolean?,
  altKey: Boolean?,
  metaKey: Boolean?,
  modifierAltGraph: Boolean?,
  modifierCapsLock: Boolean?,
  modifierFn: Boolean?,
  modifierFnLock: Boolean?,
  modifierHyper: Boolean?,
  modifierNumLock: Boolean?,
  modifierScrollLock: Boolean?,
  modifierSuper: Boolean?,
  modifierSymbol: Boolean?,
  modifierSymbolLock: Boolean?,
  view: Window?,
  detail: Int?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): WheelEventInit = org.w3c.dom.events.WheelEventInit(deltaX = deltaX, deltaY = deltaY, deltaZ = deltaZ, deltaMode = deltaMode, screenX = screenX, screenY = screenY, clientX = clientX, clientY = clientY, button = button, buttons = buttons, relatedTarget = relatedTarget, region = region, ctrlKey = ctrlKey, shiftKey = shiftKey, altKey = altKey, metaKey = metaKey, modifierAltGraph = modifierAltGraph, modifierCapsLock = modifierCapsLock, modifierFn = modifierFn, modifierFnLock = modifierFnLock, modifierHyper = modifierHyper, modifierNumLock = modifierNumLock, modifierScrollLock = modifierScrollLock, modifierSuper = modifierSuper, modifierSymbol = modifierSymbol, modifierSymbolLock = modifierSymbolLock, view = view, detail = detail, bubbles = bubbles, cancelable = cancelable, composed = composed)
