// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.workers

import org.w3c.workers.CacheStorage
import org.w3c.workers.ServiceWorkerContainer
import org.w3c.workers.UnionClientOrMessagePortOrServiceWorker
import org.w3c.workers.UnionMessagePortOrServiceWorker

public actual typealias UnionMessagePortOrServiceWorker = UnionMessagePortOrServiceWorker

public actual typealias UnionClientOrMessagePortOrServiceWorker = UnionClientOrMessagePortOrServiceWorker

public actual typealias CacheStorage = CacheStorage

public actual typealias ServiceWorkerContainer = ServiceWorkerContainer
