name: ComposeDemo
options:
  bundleIdPrefix: org.jetbrains
settings:
  DEVELOPMENT_TEAM: N462MKSJ7M
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CODE_SIGN_STYLE: Automatic
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "4"
  SDKROOT: iphoneos
targets:
  SkikoSample:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    prebuildScripts:
      - script: cd "$SRCROOT" && OUT_DIR=`pwd`/out  JAVA_TOOLS_JAR=/Users/jetbrains/jetpack_compose_ui/compose-jb/compose/scripts/../external/tools.jar  ALLOW_PUBLIC_REPOS=1  ANDROIDX_PROJECTS=compose ../../../../../gradlew  -i  -Pandroidx.compose.multiplatformEnabled=true  --no-daemon -Pkotlin.compiler.execution.strategy="in-process" -p . packForXCode
        name: GradleCompile
    info:
      path: plists/Ios/Info.plist
      properties:
    sources:
      - "src/"
    settings:
      LIBRARY_SEARCH_PATHS: "$(inherited)"
      ENABLE_BITCODE: "YES"
      ONLY_ACTIVE_ARCH: "NO"
      VALID_ARCHS: "arm64"
