// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.encryptedmedia

import kotlinx.browser.JsAny

public expect interface MediaKeySystemConfiguration : JsAny

public expect abstract class MediaKeys : JsAny
