# Reusable GitHub action needed to check YouTrack issue number in the PR description. Used by multiple Compose repositories.

name: Check YouTrack issue number in the description

inputs:
  checkout_ref:
    type: string
    default: 'master'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: JetBrains/compose-multiplatform
        ref: ${{ inputs.checkout_ref }}
        sparse-checkout: 'tools/changelog'
    - name: Check YouTrack issue number in the description
      shell: bash
      env:
        # To avoid injections as suggested in https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
        PR_DESCRIPTION: ${{ github.event.pull_request.body }}
      run: |
        cd tools/changelog
        echo "$PR_DESCRIPTION" > prDescription.txt
        kotlin changelog.main.kts action=checkIssueNumber prDescription.txt token=""
