/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.css

import kotlin.Boolean
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlinx.browser.JsAny
import kotlinx.browser.JsString
import kotlinx.browser.dom.ItemArrayLike
import kotlinx.browser.dom.definedExternally

public expect interface UnionElementOrProcessingInstruction

public expect interface ElementCSSInlineStyle : JsAny {
  public val style: CSSStyleDeclaration
}

public expect interface LinkStyle : JsAny {
  public open val sheet: StyleSheet?
}

public expect abstract class CSS : JsAny {
  public companion object {
    public fun escape(ident: String): String
  }
}

public expect abstract class CSSRule : JsAny {
  public open val type: Short

  public open var cssText: String

  public open val parentRule: CSSRule?

  public open val parentStyleSheet: CSSStyleSheet?

  public companion object {
    public val STYLE_RULE: Short

    public val CHARSET_RULE: Short

    public val IMPORT_RULE: Short

    public val MEDIA_RULE: Short

    public val FONT_FACE_RULE: Short

    public val PAGE_RULE: Short

    public val MARGIN_RULE: Short

    public val NAMESPACE_RULE: Short
  }
}

public expect abstract class CSSGroupingRule : CSSRule, JsAny {
  public open val cssRules: CSSRuleList

  public fun insertRule(rule: String, index: Int): Int

  public fun deleteRule(index: Int)

  public companion object {
    public val STYLE_RULE: Short

    public val CHARSET_RULE: Short

    public val IMPORT_RULE: Short

    public val MEDIA_RULE: Short

    public val FONT_FACE_RULE: Short

    public val PAGE_RULE: Short

    public val MARGIN_RULE: Short

    public val NAMESPACE_RULE: Short
  }
}

public expect abstract class CSSImportRule : CSSRule, JsAny {
  public open val href: String

  public open val media: MediaList

  public open val styleSheet: CSSStyleSheet

  public companion object {
    public val STYLE_RULE: Short

    public val CHARSET_RULE: Short

    public val IMPORT_RULE: Short

    public val MEDIA_RULE: Short

    public val FONT_FACE_RULE: Short

    public val PAGE_RULE: Short

    public val MARGIN_RULE: Short

    public val NAMESPACE_RULE: Short
  }
}

public expect abstract class CSSMarginRule : CSSRule, JsAny {
  public open val name: String

  public open val style: CSSStyleDeclaration

  public companion object {
    public val STYLE_RULE: Short

    public val CHARSET_RULE: Short

    public val IMPORT_RULE: Short

    public val MEDIA_RULE: Short

    public val FONT_FACE_RULE: Short

    public val PAGE_RULE: Short

    public val MARGIN_RULE: Short

    public val NAMESPACE_RULE: Short
  }
}

public expect abstract class CSSMediaRule : CSSGroupingRule, JsAny {
  public open val media: MediaList

  public companion object {
    public val STYLE_RULE: Short

    public val CHARSET_RULE: Short

    public val IMPORT_RULE: Short

    public val MEDIA_RULE: Short

    public val FONT_FACE_RULE: Short

    public val PAGE_RULE: Short

    public val MARGIN_RULE: Short

    public val NAMESPACE_RULE: Short
  }
}

public expect abstract class CSSNamespaceRule : CSSRule, JsAny {
  public open val namespaceURI: String

  public open val prefix: String

  public companion object {
    public val STYLE_RULE: Short

    public val CHARSET_RULE: Short

    public val IMPORT_RULE: Short

    public val MEDIA_RULE: Short

    public val FONT_FACE_RULE: Short

    public val PAGE_RULE: Short

    public val MARGIN_RULE: Short

    public val NAMESPACE_RULE: Short
  }
}

public expect abstract class CSSPageRule : CSSGroupingRule, JsAny {
  public open var selectorText: String

  public open val style: CSSStyleDeclaration

  public companion object {
    public val STYLE_RULE: Short

    public val CHARSET_RULE: Short

    public val IMPORT_RULE: Short

    public val MEDIA_RULE: Short

    public val FONT_FACE_RULE: Short

    public val PAGE_RULE: Short

    public val MARGIN_RULE: Short

    public val NAMESPACE_RULE: Short
  }
}

public expect abstract class CSSRuleList : ItemArrayLike<CSSRule>, JsAny {
  override fun item(index: Int): CSSRule?
}

public expect abstract class CSSStyleDeclaration : ItemArrayLike<JsString>, JsAny {
  public open var cssText: String

  public open val parentRule: CSSRule?

  public open var cssFloat: String

  public open var alignContent: String

  public open var alignItems: String

  public open var alignSelf: String

  public open var animation: String

  public open var animationDelay: String

  public open var animationDirection: String

  public open var animationDuration: String

  public open var animationFillMode: String

  public open var animationIterationCount: String

  public open var animationName: String

  public open var animationPlayState: String

  public open var animationTimingFunction: String

  public open var backfaceVisibility: String

  public open var background: String

  public open var backgroundAttachment: String

  public open var backgroundClip: String

  public open var backgroundColor: String

  public open var backgroundImage: String

  public open var backgroundOrigin: String

  public open var backgroundPosition: String

  public open var backgroundRepeat: String

  public open var backgroundSize: String

  public open var border: String

  public open var borderBottom: String

  public open var borderBottomColor: String

  public open var borderBottomLeftRadius: String

  public open var borderBottomRightRadius: String

  public open var borderBottomStyle: String

  public open var borderBottomWidth: String

  public open var borderCollapse: String

  public open var borderColor: String

  public open var borderImage: String

  public open var borderImageOutset: String

  public open var borderImageRepeat: String

  public open var borderImageSlice: String

  public open var borderImageSource: String

  public open var borderImageWidth: String

  public open var borderLeft: String

  public open var borderLeftColor: String

  public open var borderLeftStyle: String

  public open var borderLeftWidth: String

  public open var borderRadius: String

  public open var borderRight: String

  public open var borderRightColor: String

  public open var borderRightStyle: String

  public open var borderRightWidth: String

  public open var borderSpacing: String

  public open var borderStyle: String

  public open var borderTop: String

  public open var borderTopColor: String

  public open var borderTopLeftRadius: String

  public open var borderTopRightRadius: String

  public open var borderTopStyle: String

  public open var borderTopWidth: String

  public open var borderWidth: String

  public open var bottom: String

  public open var boxDecorationBreak: String

  public open var boxShadow: String

  public open var boxSizing: String

  public open var breakAfter: String

  public open var breakBefore: String

  public open var breakInside: String

  public open var captionSide: String

  public open var clear: String

  public open var clip: String

  public open var color: String

  public open var columnCount: String

  public open var columnFill: String

  public open var columnGap: String

  public open var columnRule: String

  public open var columnRuleColor: String

  public open var columnRuleStyle: String

  public open var columnRuleWidth: String

  public open var columnSpan: String

  public open var columnWidth: String

  public open var columns: String

  public open var content: String

  public open var counterIncrement: String

  public open var counterReset: String

  public open var cursor: String

  public open var direction: String

  public open var display: String

  public open var emptyCells: String

  public open var filter: String

  public open var flex: String

  public open var flexBasis: String

  public open var flexDirection: String

  public open var flexFlow: String

  public open var flexGrow: String

  public open var flexShrink: String

  public open var flexWrap: String

  public open var font: String

  public open var fontFamily: String

  public open var fontFeatureSettings: String

  public open var fontKerning: String

  public open var fontLanguageOverride: String

  public open var fontSize: String

  public open var fontSizeAdjust: String

  public open var fontStretch: String

  public open var fontStyle: String

  public open var fontSynthesis: String

  public open var fontVariant: String

  public open var fontVariantAlternates: String

  public open var fontVariantCaps: String

  public open var fontVariantEastAsian: String

  public open var fontVariantLigatures: String

  public open var fontVariantNumeric: String

  public open var fontVariantPosition: String

  public open var fontWeight: String

  public open var hangingPunctuation: String

  public open var height: String

  public open var hyphens: String

  public open var imageOrientation: String

  public open var imageRendering: String

  public open var imageResolution: String

  public open var imeMode: String

  public open var justifyContent: String

  public open var left: String

  public open var letterSpacing: String

  public open var lineBreak: String

  public open var lineHeight: String

  public open var listStyle: String

  public open var listStyleImage: String

  public open var listStylePosition: String

  public open var listStyleType: String

  public open var margin: String

  public open var marginBottom: String

  public open var marginLeft: String

  public open var marginRight: String

  public open var marginTop: String

  public open var mark: String

  public open var markAfter: String

  public open var markBefore: String

  public open var marks: String

  public open var marqueeDirection: String

  public open var marqueePlayCount: String

  public open var marqueeSpeed: String

  public open var marqueeStyle: String

  public open var mask: String

  public open var maskType: String

  public open var maxHeight: String

  public open var maxWidth: String

  public open var minHeight: String

  public open var minWidth: String

  public open var navDown: String

  public open var navIndex: String

  public open var navLeft: String

  public open var navRight: String

  public open var navUp: String

  public open var objectFit: String

  public open var objectPosition: String

  public open var opacity: String

  public open var order: String

  public open var orphans: String

  public open var outline: String

  public open var outlineColor: String

  public open var outlineOffset: String

  public open var outlineStyle: String

  public open var outlineWidth: String

  public open var overflowWrap: String

  public open var overflowX: String

  public open var overflowY: String

  public open var padding: String

  public open var paddingBottom: String

  public open var paddingLeft: String

  public open var paddingRight: String

  public open var paddingTop: String

  public open var pageBreakAfter: String

  public open var pageBreakBefore: String

  public open var pageBreakInside: String

  public open var perspective: String

  public open var perspectiveOrigin: String

  public open var phonemes: String

  public open var position: String

  public open var quotes: String

  public open var resize: String

  public open var rest: String

  public open var restAfter: String

  public open var restBefore: String

  public open var right: String

  public open var tabSize: String

  public open var tableLayout: String

  public open var textAlign: String

  public open var textAlignLast: String

  public open var textCombineUpright: String

  public open var textDecoration: String

  public open var textDecorationColor: String

  public open var textDecorationLine: String

  public open var textDecorationStyle: String

  public open var textIndent: String

  public open var textJustify: String

  public open var textOrientation: String

  public open var textOverflow: String

  public open var textShadow: String

  public open var textTransform: String

  public open var textUnderlinePosition: String

  public open var top: String

  public open var transform: String

  public open var transformOrigin: String

  public open var transformStyle: String

  public open var transition: String

  public open var transitionDelay: String

  public open var transitionDuration: String

  public open var transitionProperty: String

  public open var transitionTimingFunction: String

  public open var unicodeBidi: String

  public open var verticalAlign: String

  public open var visibility: String

  public open var voiceBalance: String

  public open var voiceDuration: String

  public open var voicePitch: String

  public open var voicePitchRange: String

  public open var voiceRate: String

  public open var voiceStress: String

  public open var voiceVolume: String

  public open var whiteSpace: String

  public open var widows: String

  public open var width: String

  public open var wordBreak: String

  public open var wordSpacing: String

  public open var wordWrap: String

  public open var writingMode: String

  public open var zIndex: String

  public open var _dashed_attribute: String

  public open var _camel_cased_attribute: String

  public open var _webkit_cased_attribute: String

  public fun getPropertyValue(`property`: String): String

  public fun getPropertyPriority(`property`: String): String

  public fun setProperty(
    `property`: String,
    `value`: String,
    priority: String = definedExternally,
  )

  public fun setPropertyValue(`property`: String, `value`: String)

  public fun setPropertyPriority(`property`: String, priority: String)

  public fun removeProperty(`property`: String): String

  override fun item(index: Int): JsString
}

public expect abstract class CSSStyleRule : CSSRule, JsAny {
  public open var selectorText: String

  public open val style: CSSStyleDeclaration

  public companion object {
    public val STYLE_RULE: Short

    public val CHARSET_RULE: Short

    public val IMPORT_RULE: Short

    public val MEDIA_RULE: Short

    public val FONT_FACE_RULE: Short

    public val PAGE_RULE: Short

    public val MARGIN_RULE: Short

    public val NAMESPACE_RULE: Short
  }
}

public expect abstract class StyleSheet : JsAny {
  public open val type: String

  public open val href: String?

  public open val ownerNode: UnionElementOrProcessingInstruction?

  public open val parentStyleSheet: StyleSheet?

  public open val title: String?

  public open val media: MediaList

  public open var disabled: Boolean
}

public expect abstract class CSSStyleSheet : StyleSheet, JsAny {
  public open val ownerRule: CSSRule?

  public open val cssRules: CSSRuleList

  public fun insertRule(rule: String, index: Int): Int

  public fun deleteRule(index: Int)
}

public expect abstract class MediaList : ItemArrayLike<JsString>, JsAny {
  public open var mediaText: String

  public fun appendMedium(medium: String)

  public fun deleteMedium(medium: String)

  override fun item(index: Int): JsString?
}

public expect abstract class StyleSheetList : ItemArrayLike<StyleSheet>, JsAny {
  override fun item(index: Int): StyleSheet?
}

public expect operator fun MediaList.`get`(index: Int): String?

public expect operator fun StyleSheetList.`get`(index: Int): StyleSheet?

public expect operator fun CSSRuleList.`get`(index: Int): CSSRule?

public expect operator fun CSSStyleDeclaration.`get`(index: Int): String?
