[versions]
compose-multiplatform = "1.10.1" # overriden via gradle.properties
kotlin = "2.3.20" # overriden via gradle.properties

[libraries]
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-html-core = { module = "org.jetbrains.compose.html:html-core", version.ref = "compose-multiplatform" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
