/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.css.masking

import kotlin.Short
import kotlinx.browser.JsAny
import kotlinx.browser.dom.svg.EmptySVGAnimatedEnumeration
import kotlinx.browser.dom.svg.EmptySVGAnimatedLength
import kotlinx.browser.dom.svg.EmptySVGAnimatedTransformList
import kotlinx.browser.dom.svg.SVGAnimatedEnumeration
import kotlinx.browser.dom.svg.SVGAnimatedLength
import kotlinx.browser.dom.svg.SVGAnimatedTransformList
import kotlinx.browser.dom.svg.SVGElement
import kotlinx.browser.dom.svg.SVGUnitTypes

public actual abstract class SVGClipPathElement : SVGElement(), SVGUnitTypes, JsAny {
  public actual open val clipPathUnits: SVGAnimatedEnumeration = EmptySVGAnimatedEnumeration

  public actual open val transform: SVGAnimatedTransformList = EmptySVGAnimatedTransformList

  public actual companion object {
    public actual val SVG_UNIT_TYPE_UNKNOWN: Short = 111

    public actual val SVG_UNIT_TYPE_USERSPACEONUSE: Short = 112

    public actual val SVG_UNIT_TYPE_OBJECTBOUNDINGBOX: Short = 110

    public actual val ELEMENT_NODE: Short = 21

    public actual val ATTRIBUTE_NODE: Short = 0

    public actual val TEXT_NODE: Short = 122

    public actual val CDATA_SECTION_NODE: Short = 4

    public actual val ENTITY_REFERENCE_NODE: Short = 25

    public actual val ENTITY_NODE: Short = 24

    public actual val PROCESSING_INSTRUCTION_NODE: Short = 59

    public actual val COMMENT_NODE: Short = 9

    public actual val DOCUMENT_NODE: Short = 12

    public actual val DOCUMENT_TYPE_NODE: Short = 19

    public actual val DOCUMENT_FRAGMENT_NODE: Short = 11

    public actual val NOTATION_NODE: Short = 55

    public actual val DOCUMENT_POSITION_DISCONNECTED: Short = 15

    public actual val DOCUMENT_POSITION_PRECEDING: Short = 18

    public actual val DOCUMENT_POSITION_FOLLOWING: Short = 16

    public actual val DOCUMENT_POSITION_CONTAINS: Short = 14

    public actual val DOCUMENT_POSITION_CONTAINED_BY: Short = 13

    public actual val DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: Short = 17
  }
}

public actual abstract class SVGMaskElement : SVGElement(), SVGUnitTypes, JsAny {
  public actual open val maskUnits: SVGAnimatedEnumeration = EmptySVGAnimatedEnumeration

  public actual open val maskContentUnits: SVGAnimatedEnumeration = EmptySVGAnimatedEnumeration

  public actual open val x: SVGAnimatedLength = EmptySVGAnimatedLength

  public actual open val y: SVGAnimatedLength = EmptySVGAnimatedLength

  public actual open val width: SVGAnimatedLength = EmptySVGAnimatedLength

  public actual open val height: SVGAnimatedLength = EmptySVGAnimatedLength

  public actual companion object {
    public actual val SVG_UNIT_TYPE_UNKNOWN: Short = 111

    public actual val SVG_UNIT_TYPE_USERSPACEONUSE: Short = 112

    public actual val SVG_UNIT_TYPE_OBJECTBOUNDINGBOX: Short = 110

    public actual val ELEMENT_NODE: Short = 21

    public actual val ATTRIBUTE_NODE: Short = 0

    public actual val TEXT_NODE: Short = 122

    public actual val CDATA_SECTION_NODE: Short = 4

    public actual val ENTITY_REFERENCE_NODE: Short = 25

    public actual val ENTITY_NODE: Short = 24

    public actual val PROCESSING_INSTRUCTION_NODE: Short = 59

    public actual val COMMENT_NODE: Short = 9

    public actual val DOCUMENT_NODE: Short = 12

    public actual val DOCUMENT_TYPE_NODE: Short = 19

    public actual val DOCUMENT_FRAGMENT_NODE: Short = 11

    public actual val NOTATION_NODE: Short = 55

    public actual val DOCUMENT_POSITION_DISCONNECTED: Short = 15

    public actual val DOCUMENT_POSITION_PRECEDING: Short = 18

    public actual val DOCUMENT_POSITION_FOLLOWING: Short = 16

    public actual val DOCUMENT_POSITION_CONTAINS: Short = 14

    public actual val DOCUMENT_POSITION_CONTAINED_BY: Short = 13

    public actual val DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: Short = 17
  }
}
