// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.clipboard

import kotlin.Boolean
import kotlin.Suppress
import kotlinx.browser.JsAny
import kotlinx.browser.dom.DataTransfer
import kotlinx.browser.dom.EventInit

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ClipboardEventInit : EventInit, JsAny {
  public var clipboardData: DataTransfer?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ClipboardPermissionDescriptor : JsAny {
  public var allowWithoutGesture: Boolean?
}

public expect fun ClipboardEventInit(
  clipboardData: DataTransfer? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): ClipboardEventInit

public expect fun ClipboardPermissionDescriptor(allowWithoutGesture: Boolean? = null): ClipboardPermissionDescriptor
