// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.clipboard

import kotlinx.browser.JsAny
import kotlinx.browser.dom.events.Event
import kotlinx.browser.dom.events.EventTarget

public expect abstract class Clipboard : EventTarget, JsAny

public expect open class ClipboardEvent : Event, JsAny
