/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
@file:Suppress(
  "DEFAULT_ARGUMENTS_IN_EXPECT_WITH_ACTUAL_TYPEALIAS",
  "EXPECT_ACTUAL_INCOMPATIBLE_CLASS_SCOPE",
)

package kotlinx.browser.dom.css

import kotlin.Int
import kotlin.String
import kotlin.Suppress
import org.w3c.dom.css.CSS
import org.w3c.dom.css.CSSGroupingRule
import org.w3c.dom.css.CSSImportRule
import org.w3c.dom.css.CSSMarginRule
import org.w3c.dom.css.CSSMediaRule
import org.w3c.dom.css.CSSNamespaceRule
import org.w3c.dom.css.CSSPageRule
import org.w3c.dom.css.CSSStyleRule
import org.w3c.dom.css.CSSStyleSheet
import org.w3c.dom.css.ElementCSSInlineStyle
import org.w3c.dom.css.LinkStyle
import org.w3c.dom.css.UnionElementOrProcessingInstruction
import org.w3c.dom.css.`get` as browserGet

public actual typealias UnionElementOrProcessingInstruction = UnionElementOrProcessingInstruction

public actual typealias ElementCSSInlineStyle = ElementCSSInlineStyle

public actual typealias LinkStyle = LinkStyle

public actual typealias CSS = CSS

public actual typealias CSSRule = org.w3c.dom.css.CSSRule

public actual typealias CSSGroupingRule = CSSGroupingRule

public actual typealias CSSImportRule = CSSImportRule

public actual typealias CSSMarginRule = CSSMarginRule

public actual typealias CSSMediaRule = CSSMediaRule

public actual typealias CSSNamespaceRule = CSSNamespaceRule

public actual typealias CSSPageRule = CSSPageRule

public actual typealias CSSRuleList = org.w3c.dom.css.CSSRuleList

public actual typealias CSSStyleDeclaration = org.w3c.dom.css.CSSStyleDeclaration

public actual typealias CSSStyleRule = CSSStyleRule

public actual typealias StyleSheet = org.w3c.dom.css.StyleSheet

public actual typealias CSSStyleSheet = CSSStyleSheet

public actual typealias MediaList = org.w3c.dom.css.MediaList

public actual typealias StyleSheetList = org.w3c.dom.css.StyleSheetList

public actual operator fun MediaList.`get`(index: Int): String? = this.browserGet(index)

public actual operator fun StyleSheetList.`get`(index: Int): StyleSheet? = this.browserGet(index)

public actual operator fun CSSRuleList.`get`(index: Int): CSSRule? = this.browserGet(index)

public actual operator fun CSSStyleDeclaration.`get`(index: Int): String? = this.browserGet(index)
