// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom

import kotlin.Nothing
import kotlin.UnsupportedOperationException

/**
 * Placeholder for `kotlin.js.definedExternally` in common declarations; never evaluated.
 */
public val definedExternally: Nothing
  get() = throw UnsupportedOperationException("definedExternally is never evaluated")
