/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom

import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlinx.browser.JsAny
import kotlinx.browser.JsArray
import kotlinx.browser.JsString
import kotlinx.browser.Promise
import kotlinx.browser.dom.events.EventTarget
import kotlinx.browser.dom.events.MouseEventInit
import kotlinx.browser.fetch.RequestCredentials

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface EventListenerOptions : JsAny {
  public var capture: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface AddEventListenerOptions : EventListenerOptions, JsAny {
  public var passive: Boolean?

  public var once: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface AssignedNodesOptions : JsAny {
  public var flatten: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface BoxQuadOptions : JsAny {
  public var box: CSSBoxType?

  public var relativeTo: JsAny?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface CanvasRenderingContext2DSettings : JsAny {
  public var alpha: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface EventInit : JsAny {
  public var bubbles: Boolean?

  public var cancelable: Boolean?

  public var composed: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface CloseEventInit : EventInit, JsAny {
  public var wasClean: Boolean?

  public var code: Short?

  public var reason: String?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ConvertCoordinateOptions : JsAny {
  public var fromBox: CSSBoxType?

  public var toBox: CSSBoxType?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface CustomEventInit : EventInit, JsAny {
  public var detail: JsAny?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface DOMPointInit : JsAny {
  public var x: Double?

  public var y: Double?

  public var z: Double?

  public var w: Double?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface DOMRectInit : JsAny {
  public var x: Double?

  public var y: Double?

  public var width: Double?

  public var height: Double?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface DragEventInit : MouseEventInit, JsAny {
  public var dataTransfer: DataTransfer?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ElementCreationOptions : JsAny {
  public var `is`: String?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ElementDefinitionOptions : JsAny {
  public var extends: String?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ErrorEventInit : EventInit, JsAny {
  public var message: String?

  public var filename: String?

  public var lineno: Int?

  public var colno: Int?

  public var error: JsAny?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface EventSourceInit : JsAny {
  public var withCredentials: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface GetRootNodeOptions : JsAny {
  public var composed: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface HashChangeEventInit : EventInit, JsAny {
  public var oldURL: String?

  public var newURL: String?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface HitRegionOptions : JsAny {
  public var path: Path2D?

  public var fillRule: CanvasFillRule?

  public var id: String?

  public var parentID: String?

  public var cursor: String?

  public var control: Element?

  public var label: String?

  public var role: String?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ImageBitmapOptions : JsAny {
  public var imageOrientation: ImageOrientation?

  public var premultiplyAlpha: PremultiplyAlpha?

  public var colorSpaceConversion: ColorSpaceConversion?

  public var resizeWidth: Int?

  public var resizeHeight: Int?

  public var resizeQuality: ResizeQuality?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ImageBitmapRenderingContextSettings : JsAny {
  public var alpha: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface MediaQueryListEventInit : EventInit, JsAny {
  public var media: String?

  public var matches: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface MessageEventInit : EventInit, JsAny {
  public var `data`: JsAny?

  public var origin: String?

  public var lastEventId: String?

  public var source: UnionMessagePortOrWindowProxy?

  public var ports: JsArray<MessagePort>?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface MutationObserverInit : JsAny {
  public var childList: Boolean?

  public var attributes: Boolean?

  public var characterData: Boolean?

  public var subtree: Boolean?

  public var attributeOldValue: Boolean?

  public var characterDataOldValue: Boolean?

  public var attributeFilter: JsArray<JsString>?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface PageTransitionEventInit : EventInit, JsAny {
  public var persisted: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface PopStateEventInit : EventInit, JsAny {
  public var state: JsAny?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface PromiseRejectionEventInit : EventInit, JsAny {
  public var promise: Promise<*>?

  public var reason: JsAny?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface RelatedEventInit : EventInit, JsAny {
  public var relatedTarget: EventTarget?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ScrollOptions : JsAny {
  public var behavior: ScrollBehavior?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ScrollIntoViewOptions : ScrollOptions, JsAny {
  public var block: ScrollLogicalPosition?

  public var `inline`: ScrollLogicalPosition?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ScrollToOptions : ScrollOptions, JsAny {
  public var left: Double?

  public var top: Double?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface ShadowRootInit : JsAny {
  public var mode: ShadowRootMode?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface StorageEventInit : EventInit, JsAny {
  public var key: String?

  public var oldValue: String?

  public var newValue: String?

  public var url: String?

  public var storageArea: Storage?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface TrackEventInit : EventInit, JsAny {
  public var track: UnionAudioTrackOrTextTrackOrVideoTrack?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface WorkerOptions : JsAny {
  public var type: WorkerType?

  public var credentials: RequestCredentials?
}

public expect fun EventListenerOptions(capture: Boolean? = null): EventListenerOptions

public expect fun AddEventListenerOptions(
  passive: Boolean? = null,
  once: Boolean? = null,
  capture: Boolean? = null,
): AddEventListenerOptions

public expect fun AssignedNodesOptions(flatten: Boolean? = null): AssignedNodesOptions

public expect fun BoxQuadOptions(box: CSSBoxType? = null, relativeTo: JsAny? = null): BoxQuadOptions

public expect fun CanvasRenderingContext2DSettings(alpha: Boolean? = null): CanvasRenderingContext2DSettings

public expect fun EventInit(
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): EventInit

public expect fun CloseEventInit(
  wasClean: Boolean? = null,
  code: Short? = null,
  reason: String? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): CloseEventInit

public expect fun ConvertCoordinateOptions(fromBox: CSSBoxType? = null, toBox: CSSBoxType? = null): ConvertCoordinateOptions

public expect fun CustomEventInit(
  detail: JsAny? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): CustomEventInit

public expect fun DOMPointInit(
  x: Double? = null,
  y: Double? = null,
  z: Double? = null,
  w: Double? = null,
): DOMPointInit

public expect fun DOMRectInit(
  x: Double? = null,
  y: Double? = null,
  width: Double? = null,
  height: Double? = null,
): DOMRectInit

public expect fun DragEventInit(
  dataTransfer: DataTransfer? = null,
  screenX: Int? = null,
  screenY: Int? = null,
  clientX: Int? = null,
  clientY: Int? = null,
  button: Short? = null,
  buttons: Short? = null,
  relatedTarget: EventTarget? = null,
  region: String? = null,
  ctrlKey: Boolean? = null,
  shiftKey: Boolean? = null,
  altKey: Boolean? = null,
  metaKey: Boolean? = null,
  modifierAltGraph: Boolean? = null,
  modifierCapsLock: Boolean? = null,
  modifierFn: Boolean? = null,
  modifierFnLock: Boolean? = null,
  modifierHyper: Boolean? = null,
  modifierNumLock: Boolean? = null,
  modifierScrollLock: Boolean? = null,
  modifierSuper: Boolean? = null,
  modifierSymbol: Boolean? = null,
  modifierSymbolLock: Boolean? = null,
  view: Window? = null,
  detail: Int? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): DragEventInit

public expect fun ElementCreationOptions(param_is: String? = null): ElementCreationOptions

public expect fun ElementDefinitionOptions(extends_: String? = null): ElementDefinitionOptions

public expect fun ErrorEventInit(
  message: String? = null,
  filename: String? = null,
  lineno: Int? = null,
  colno: Int? = null,
  error: JsAny? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): ErrorEventInit

public expect fun EventSourceInit(withCredentials: Boolean? = null): EventSourceInit

public expect fun GetRootNodeOptions(composed: Boolean? = null): GetRootNodeOptions

public expect fun HashChangeEventInit(
  oldURL: String? = null,
  newURL: String? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): HashChangeEventInit

public expect fun HitRegionOptions(
  path: Path2D? = null,
  fillRule: CanvasFillRule? = null,
  id: String? = null,
  parentID: String? = null,
  cursor: String? = null,
  control: Element? = null,
  label: String? = null,
  role: String? = null,
): HitRegionOptions

public expect fun ImageBitmapOptions(
  imageOrientation: ImageOrientation? = null,
  premultiplyAlpha: PremultiplyAlpha? = null,
  colorSpaceConversion: ColorSpaceConversion? = null,
  resizeWidth: Int? = null,
  resizeHeight: Int? = null,
  resizeQuality: ResizeQuality? = null,
): ImageBitmapOptions

public expect fun ImageBitmapRenderingContextSettings(alpha: Boolean? = null): ImageBitmapRenderingContextSettings

public expect fun MediaQueryListEventInit(
  media: String? = null,
  matches: Boolean? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): MediaQueryListEventInit

public expect fun MessageEventInit(
  `data`: JsAny? = null,
  origin: String? = null,
  lastEventId: String? = null,
  source: UnionMessagePortOrWindowProxy? = null,
  ports: JsArray<MessagePort>? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): MessageEventInit

public expect fun MutationObserverInit(
  childList: Boolean? = null,
  attributes: Boolean? = null,
  characterData: Boolean? = null,
  subtree: Boolean? = null,
  attributeOldValue: Boolean? = null,
  characterDataOldValue: Boolean? = null,
  attributeFilter: JsArray<JsString>? = null,
): MutationObserverInit

public expect fun PageTransitionEventInit(
  persisted: Boolean? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): PageTransitionEventInit

public expect fun PopStateEventInit(
  state: JsAny? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): PopStateEventInit

public expect fun PromiseRejectionEventInit(
  promise: Promise<*>? = null,
  reason: JsAny? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): PromiseRejectionEventInit

public expect fun RelatedEventInit(
  relatedTarget: EventTarget? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): RelatedEventInit

public expect fun ScrollOptions(behavior: ScrollBehavior? = null): ScrollOptions

public expect fun ScrollIntoViewOptions(
  block: ScrollLogicalPosition? = null,
  `inline`: ScrollLogicalPosition? = null,
  behavior: ScrollBehavior? = null,
): ScrollIntoViewOptions

public expect fun ScrollToOptions(
  left: Double? = null,
  top: Double? = null,
  behavior: ScrollBehavior? = null,
): ScrollToOptions

public expect fun ShadowRootInit(mode: ShadowRootMode? = null): ShadowRootInit

public expect fun StorageEventInit(
  key: String? = null,
  oldValue: String? = null,
  newValue: String? = null,
  url: String? = null,
  storageArea: Storage? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): StorageEventInit

public expect fun TrackEventInit(
  track: UnionAudioTrackOrTextTrackOrVideoTrack? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): TrackEventInit

public expect fun WorkerOptions(type: WorkerType? = null, credentials: RequestCredentials? = null): WorkerOptions
