/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Emits common and browser facade source files.
package org.jetbrains.compose.web.browser.generator

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.NOTHING
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeAliasSpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.TypeVariableName
import com.squareup.kotlinpoet.UNIT

// Shared KotlinPoet builders.

internal val PortableClass.isInterface: Boolean
    get() = shape == ClassShape.INTERFACE

internal fun PortableClass.typeBuilder(): TypeSpec.Builder = when (shape) {
    ClassShape.INTERFACE -> TypeSpec.interfaceBuilder(portableName)
    else -> TypeSpec.classBuilder(portableName)
}

internal fun PortableParameter.spec(default: CodeBlock?): ParameterSpec =
    ParameterSpec.builder(name, type, *(if (isVararg) arrayOf(KModifier.VARARG) else emptyArray()))
        .apply { default?.let(::defaultValue) }
        .build()

internal fun PortableFunction.specBuilder(
    parameterSpec: (PortableParameter) -> ParameterSpec,
): FunSpec.Builder {
    val builder = FunSpec.builder(name).addParameters(parameters.map(parameterSpec))
    if (returnType != UNIT) builder.returns(returnType)
    return builder
}

internal fun FileSpec.Builder.generatedComment(): FileSpec.Builder =
    addFileComment("Generated by the kotlinx-browser common subset generator. Do not edit.")

/** A generated facade file: the shared header comment followed by [configure]'s content. */
internal inline fun facadeFile(
    packageName: String,
    fileName: String,
    configure: FileSpec.Builder.() -> Unit,
): FileSpec = FileSpec.builder(packageName, fileName).generatedComment().apply(configure).build()

internal fun FileSpec.Builder.suppress(vararg names: String): FileSpec.Builder = addAnnotation(
    suppression(*names).toBuilder().useSiteTarget(AnnotationSpec.UseSiteTarget.FILE).build(),
)

internal fun suppression(vararg names: String): AnnotationSpec =
    AnnotationSpec.builder(Suppress::class)
        .apply { names.forEach { addMember("%S", it) } }
        .build()

// Common emitters.

internal fun commonCoreFile(): FileSpec = facadeFile(PORTABLE_DOM_PACKAGE, "Core") {
    addProperty(
        PropertySpec.builder(DEFINED_EXTERNALLY.simpleName, NOTHING)
            .addModifiers(KModifier.PUBLIC)
            .addKdoc("Placeholder for `kotlin.js.definedExternally` in common declarations; never evaluated.")
            .getter(
                FunSpec.getterBuilder()
                    .addStatement(
                        "throw %T(%S)",
                        ClassName("kotlin", "UnsupportedOperationException"),
                        "definedExternally is never evaluated",
                    )
                    .build(),
            )
            .build(),
    )
}

internal fun commonDeclarationsFile(
    mapping: PortablePackageMapping,
    declarations: List<PortableClass>,
    extensions: List<PortableExtensionFunction>,
): FileSpec = facadeFile(mapping.portablePackage, mapping.declarationsFile) {
    declarations.forEach { addType(it.commonType()) }
    extensions.forEach { addFunction(it.webSpec(actual = false)) }
}

internal fun commonValuesFile(
    mapping: PortablePackageMapping,
    values: List<PortableExtensionValue>,
): FileSpec = facadeFile(mapping.portablePackage, mapping.valuesFile) {
    values.forEach { addProperty(it.webSpec(actual = false)) }
}

internal fun commonDictionariesFile(
    mapping: PortablePackageMapping,
    dictionaries: List<PortableClass>,
): FileSpec = facadeFile(mapping.portablePackage, mapping.dictionariesFile) {
    dictionaries.forEach { addType(it.commonType()) }
    dictionaries.forEach { dictionary ->
        dictionary.factory?.let { addFunction(dictionary.webFactory(it, actual = false)) }
    }
}

// Common declaration specs.

private fun PortableClass.commonType(): TypeSpec = typeBuilder()
    .addModifiers(KModifier.PUBLIC, KModifier.EXPECT)
    .apply {
        shape.modifier?.let { addModifiers(it) }
        this@commonType.typeVariables.forEach(::addTypeVariable)
        if (needsIrSuppression) addAnnotation(suppression(IR_SUPPRESSION))
        portableParentName?.let(::addSuperinterface)
        portableSuperinterfaces.forEach { addSuperinterface(it) }
        if (isJsAny) addSuperinterface(PORTABLE_JS_ANY)
        constructors.firstOrNull(PortableConstructor::primary)?.let { primaryConstructor(it.commonSpec()) }
        constructors.filterNot(PortableConstructor::primary).forEach { addFunction(it.commonSpec()) }
        properties.forEach { addProperty(it.commonSpec(isInterface, openWhenDefault = isInterface && !isDictionary)) }
        functions.forEach { addFunction(it.commonSpec(isInterface)) }
        companion?.let { addType(it.commonSpec()) }
    }
    .build()

private fun PortableCompanion.commonSpec(): TypeSpec = TypeSpec.companionObjectBuilder()
    .apply {
        properties.forEach { addProperty(it.commonSpec()) }
        functions.forEach { addFunction(it.commonSpec(abstract = false)) }
    }
    .build()

private fun PortableConstant.commonSpec(): PropertySpec = PropertySpec.builder(name, type).build()

private fun PortableConstructor.commonSpec(): FunSpec {
    val constructor = this
    return FunSpec.constructorBuilder()
        .apply {
            constructor.parameters.forEach { addParameter(it.commonParameter()) }
        }
        .build()
}

private fun PortableProperty.commonSpec(abstract: Boolean, openWhenDefault: Boolean = false): PropertySpec =
    PropertySpec.builder(name, type)
        .mutable(mutable)
        .apply {
            when {
                overrides -> addModifiers(KModifier.OVERRIDE)
                open && !abstract -> addModifiers(KModifier.OPEN)
                // Browser default accessors need an open expect so web aliases and JVM defaults agree.
                // Dictionaries remain abstract and use their IR suppression.
                openWhenDefault && !abstractInBrowser -> addModifiers(KModifier.OPEN)
            }
        }
        .build()

private fun PortableFunction.commonSpec(abstract: Boolean): FunSpec =
    specBuilder(PortableParameter::commonParameter)
        .apply {
            when {
                overrides -> addModifiers(KModifier.OVERRIDE)
                open && !abstract -> addModifiers(KModifier.OPEN)
            }
        }
        .build()

private fun PortableExtensionFunction.webSpec(actual: Boolean): FunSpec {
    val extension = this
    val arguments = function.parameters.joinToString { it.name }
    // Actual wrappers cannot share web-only defaults; omitted defaults could evaluate the common
    // throwing placeholder, so every wrapper argument stays explicit.
    return function.specBuilder { it.spec(default = null) }
        .receiver(receiverType)
        .addModifiers(KModifier.PUBLIC, if (actual) KModifier.ACTUAL else KModifier.EXPECT, KModifier.OPERATOR)
        .apply {
            if (actual) {
                addStatement(
                    if (extension.function.returnType == UNIT) "this.%M(%L)" else "return this.%M(%L)",
                    browserMember, arguments,
                )
            }
        }
        .build()
}

private fun PortableParameter.commonParameter(): ParameterSpec =
    spec(if (hasDefault) CodeBlock.of("%M", DEFINED_EXTERNALLY) else null)

private fun PortableExtensionValue.webSpec(actual: Boolean): PropertySpec =
    PropertySpec.builder(name, portableOwner)
        .addModifiers(KModifier.PUBLIC, if (actual) KModifier.ACTUAL else KModifier.EXPECT)
        .receiver(if (actual) browserOwner.companionName() else portableOwner.companionName())
        .apply {
            if (actual) {
                getter(FunSpec.getterBuilder().addStatement("return %T.%M", browserOwner, browserMember).build())
            }
        }
        .build()

private fun PortableClass.webFactory(factory: PortableFactory, actual: Boolean): FunSpec =
    FunSpec.builder(portableName.simpleName)
        .addModifiers(KModifier.PUBLIC, if (actual) KModifier.ACTUAL else KModifier.EXPECT)
        .returns(portableName)
        .apply {
            factory.parameters.forEach {
                // Common factories use inert defaults; browser actuals leave defaults to the platform.
                val default = if (actual) null else inertLiteral(it.type)
                addParameter(it.spec(default))
            }
            if (actual) {
                addStatement(
                    "return %L(%L)",
                    browserName.canonicalName,
                    factory.parameters.joinToString { "${it.name} = ${it.name}" },
                )
            }
        }
        .build()

// Browser leaf emitters.

/** Emits browser-backed actual declarations shared by the JS and Wasm/JS leaf outputs. */
internal fun browserLeafDeclarationsFile(
    mapping: PortablePackageMapping,
    declarations: List<PortableClass>,
    extensions: List<PortableExtensionFunction>,
): FileSpec = facadeFile(mapping.portablePackage, mapping.declarationsFile) {
    webSuppressions(declarations)
    extensions.distinctBy(PortableExtensionFunction::browserMember).forEach { extension ->
        addAliasedImport(extension.browserMember, extension.browserAlias)
    }
    declarations.forEach { addTypeAlias(it.browserTypeAlias()) }
    extensions.forEach { addFunction(it.webSpec(actual = true)) }
}

/** Emits actual wrappers with target-specific interop types into each browser leaf source set. */
internal fun targetDeclarationsFile(
    mapping: PortablePackageMapping,
    extensions: List<PortableExtensionFunction>,
    dictionaries: List<PortableClass>,
): FileSpec = facadeFile(mapping.portablePackage, mapping.interopFile) {
    extensions.distinctBy(PortableExtensionFunction::browserMember).forEach { extension ->
        addAliasedImport(extension.browserMember, extension.browserAlias)
    }
    extensions.forEach { addFunction(it.webSpec(actual = true)) }
    dictionaries.forEach { dictionary ->
        dictionary.factory?.let { addFunction(dictionary.webFactory(it, actual = true)) }
    }
}

/** Emits browser-backed enum-like values into each browser leaf source set. */
internal fun targetValuesFile(
    mapping: PortablePackageMapping,
    values: List<PortableExtensionValue>,
): FileSpec = facadeFile(mapping.portablePackage, mapping.valuesFile) {
    values.distinctBy(PortableExtensionValue::browserOwner).forEach { value ->
        addAliasedImport(value.browserOwner, value.browserOwner.browserImportAlias())
    }
    values.forEach { addAliasedImport(it.browserMember, it.browserAlias) }
    values.forEach { addProperty(it.webSpec(actual = true)) }
}

/** Emits dictionary aliases and factories that need no target-specific interop. */
internal fun browserLeafDictionariesFile(
    mapping: PortablePackageMapping,
    dictionaries: List<PortableClass>,
): FileSpec = facadeFile(mapping.portablePackage, mapping.dictionariesFile) {
    webSuppressions(dictionaries)
    dictionaries.forEach { addTypeAlias(it.browserTypeAlias()) }
    dictionaries.forEach { dictionary ->
        dictionary.factory?.takeUnless(PortableFactory::usesInterop)
            ?.let { addFunction(dictionary.webFactory(it, actual = true)) }
    }
}

private fun PortableClass.browserTypeAlias(): TypeAliasSpec =
    browserAliasTypeVariables().let { aliases ->
        TypeAliasSpec.builder(
            portableName.simpleName,
            if (aliases.isEmpty()) browserName else browserName.parameterizedBy(aliases),
        )
            .addModifiers(KModifier.PUBLIC, KModifier.ACTUAL)
            .apply { aliases.forEach(::addTypeVariable) }
            .build()
    }

/** Typealias parameters are invariant even when the aliased interface declares variance. */
private fun PortableClass.browserAliasTypeVariables() =
    typeVariables.map { variable -> TypeVariableName(variable.name) }

private fun FileSpec.Builder.webSuppressions(classes: List<PortableClass>): FileSpec.Builder =
    suppressIfAny(buildList {
        // Each suppression answers a distinct declaration shape; keep their file checks independent.
        if (classes.any(PortableClass::hasDefaultArguments)) {
            add(DEFAULT_ARGUMENTS_SUPPRESSION)
        }
        if (classes.any { it.needsIrSuppression || it.hasDefaultArguments }) {
            add(CLASS_SCOPE_SUPPRESSION)
        }
        if (classes.any { it.typeVariables.any { variable -> variable.variance != null } }) {
            add(VARIANCE_SUPPRESSION)
        }
    })

internal fun FileSpec.Builder.suppressIfAny(names: List<String>): FileSpec.Builder =
    if (names.isEmpty()) this else suppress(*names.distinct().toTypedArray())
