/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser

import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.MutableList

public actual interface JsAny

/**
 * Inert `JsAny` value used by JVM stubs.
 */
internal object EmptyJsAny : JsAny

public actual class JsString internal constructor(
  internal val `value`: String,
) : JsAny {
  override fun toString(): String = value
}

public actual fun String.toJsString(): JsString = JsString(this)

public actual fun JsString.toKotlinString(): String = value

public actual abstract class JsNumber : JsAny {
  internal abstract val `value`: Double
}

private class JvmJsNumber(
  override val `value`: Double,
) : JsNumber()

public actual fun Double.toJsNumber(): JsNumber = JvmJsNumber(this)

public actual fun JsNumber.toDouble(): Double = value

public actual class JsDouble internal constructor(
  internal val `value`: Double,
) : JsAny

public actual fun Double.toJsDouble(): JsDouble = JsDouble(this)

public actual fun JsDouble.toKotlinDouble(): Double = value

public actual class JsArray<T : JsAny?> internal constructor(
  private val values: MutableList<T?> = mutableListOf(),
) : JsAny {
  internal val size: Int
    get() = values.size

  internal fun elementAtOrNull(index: Int): T? = values.getOrNull(index)

  internal fun put(index: Int, `value`: T) {
    while (values.size <= index) {
      values += null
    }
    values[index] = value
  }

  @Suppress("UNCHECKED_CAST")
  internal fun snapshot(): List<T> = values.toList() as List<T>
}

public actual val JsArray<*>.length: Int
  get() = size

public actual operator fun <T : JsAny?> JsArray<T>.`get`(index: Int): T? = elementAtOrNull(index)

public actual operator fun <T : JsAny?> JsArray<T>.`set`(index: Int, `value`: T) {
  put(index, value)
}

public actual fun <T : JsAny?> JsArray<T>.toList(): List<T> = snapshot()

public actual fun <T : JsAny?> List<T>.toJsArray(): JsArray<T> = JsArray(toMutableList<T?>())

public actual class Promise<out T : JsAny?> internal constructor() : JsAny
