// Generated by the kotlinx-browser common subset generator. Do not edit.
@file:Suppress("EXPECT_ACTUAL_INCOMPATIBLE_CLASS_SCOPE")

package kotlinx.browser.dom

import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlinx.browser.dom.events.EventTarget
import kotlinx.browser.fetch.RequestCredentials
import org.w3c.dom.BoxQuadOptions
import org.w3c.dom.CustomEventInit
import org.w3c.dom.ErrorEventInit
import org.w3c.dom.MessageEventInit
import org.w3c.dom.MutationObserverInit
import org.w3c.dom.PopStateEventInit
import org.w3c.dom.PromiseRejectionEventInit

public actual typealias EventListenerOptions = org.w3c.dom.EventListenerOptions

public actual typealias AddEventListenerOptions = org.w3c.dom.AddEventListenerOptions

public actual typealias AssignedNodesOptions = org.w3c.dom.AssignedNodesOptions

public actual typealias BoxQuadOptions = BoxQuadOptions

public actual typealias CanvasRenderingContext2DSettings = org.w3c.dom.CanvasRenderingContext2DSettings

public actual typealias EventInit = org.w3c.dom.EventInit

public actual typealias CloseEventInit = org.w3c.dom.CloseEventInit

public actual typealias ConvertCoordinateOptions = org.w3c.dom.ConvertCoordinateOptions

public actual typealias CustomEventInit = CustomEventInit

public actual typealias DOMPointInit = org.w3c.dom.DOMPointInit

public actual typealias DOMRectInit = org.w3c.dom.DOMRectInit

public actual typealias DragEventInit = org.w3c.dom.DragEventInit

public actual typealias ElementCreationOptions = org.w3c.dom.ElementCreationOptions

public actual typealias ElementDefinitionOptions = org.w3c.dom.ElementDefinitionOptions

public actual typealias ErrorEventInit = ErrorEventInit

public actual typealias EventSourceInit = org.w3c.dom.EventSourceInit

public actual typealias GetRootNodeOptions = org.w3c.dom.GetRootNodeOptions

public actual typealias HashChangeEventInit = org.w3c.dom.HashChangeEventInit

public actual typealias HitRegionOptions = org.w3c.dom.HitRegionOptions

public actual typealias ImageBitmapOptions = org.w3c.dom.ImageBitmapOptions

public actual typealias ImageBitmapRenderingContextSettings = org.w3c.dom.ImageBitmapRenderingContextSettings

public actual typealias MediaQueryListEventInit = org.w3c.dom.MediaQueryListEventInit

public actual typealias MessageEventInit = MessageEventInit

public actual typealias MutationObserverInit = MutationObserverInit

public actual typealias PageTransitionEventInit = org.w3c.dom.PageTransitionEventInit

public actual typealias PopStateEventInit = PopStateEventInit

public actual typealias PromiseRejectionEventInit = PromiseRejectionEventInit

public actual typealias RelatedEventInit = org.w3c.dom.RelatedEventInit

public actual typealias ScrollOptions = org.w3c.dom.ScrollOptions

public actual typealias ScrollIntoViewOptions = org.w3c.dom.ScrollIntoViewOptions

public actual typealias ScrollToOptions = org.w3c.dom.ScrollToOptions

public actual typealias ShadowRootInit = org.w3c.dom.ShadowRootInit

public actual typealias StorageEventInit = org.w3c.dom.StorageEventInit

public actual typealias TrackEventInit = org.w3c.dom.TrackEventInit

public actual typealias WorkerOptions = org.w3c.dom.WorkerOptions

public actual fun EventListenerOptions(capture: Boolean?): EventListenerOptions = org.w3c.dom.EventListenerOptions(capture = capture)

public actual fun AddEventListenerOptions(
  passive: Boolean?,
  once: Boolean?,
  capture: Boolean?,
): AddEventListenerOptions = org.w3c.dom.AddEventListenerOptions(passive = passive, once = once, capture = capture)

public actual fun AssignedNodesOptions(flatten: Boolean?): AssignedNodesOptions = org.w3c.dom.AssignedNodesOptions(flatten = flatten)

public actual fun CanvasRenderingContext2DSettings(alpha: Boolean?): CanvasRenderingContext2DSettings = org.w3c.dom.CanvasRenderingContext2DSettings(alpha = alpha)

public actual fun EventInit(
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): EventInit = org.w3c.dom.EventInit(bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun CloseEventInit(
  wasClean: Boolean?,
  code: Short?,
  reason: String?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): CloseEventInit = org.w3c.dom.CloseEventInit(wasClean = wasClean, code = code, reason = reason, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun ConvertCoordinateOptions(fromBox: CSSBoxType?, toBox: CSSBoxType?): ConvertCoordinateOptions = org.w3c.dom.ConvertCoordinateOptions(fromBox = fromBox, toBox = toBox)

public actual fun DOMPointInit(
  x: Double?,
  y: Double?,
  z: Double?,
  w: Double?,
): DOMPointInit = org.w3c.dom.DOMPointInit(x = x, y = y, z = z, w = w)

public actual fun DOMRectInit(
  x: Double?,
  y: Double?,
  width: Double?,
  height: Double?,
): DOMRectInit = org.w3c.dom.DOMRectInit(x = x, y = y, width = width, height = height)

public actual fun DragEventInit(
  dataTransfer: DataTransfer?,
  screenX: Int?,
  screenY: Int?,
  clientX: Int?,
  clientY: Int?,
  button: Short?,
  buttons: Short?,
  relatedTarget: EventTarget?,
  region: String?,
  ctrlKey: Boolean?,
  shiftKey: Boolean?,
  altKey: Boolean?,
  metaKey: Boolean?,
  modifierAltGraph: Boolean?,
  modifierCapsLock: Boolean?,
  modifierFn: Boolean?,
  modifierFnLock: Boolean?,
  modifierHyper: Boolean?,
  modifierNumLock: Boolean?,
  modifierScrollLock: Boolean?,
  modifierSuper: Boolean?,
  modifierSymbol: Boolean?,
  modifierSymbolLock: Boolean?,
  view: Window?,
  detail: Int?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): DragEventInit = org.w3c.dom.DragEventInit(dataTransfer = dataTransfer, screenX = screenX, screenY = screenY, clientX = clientX, clientY = clientY, button = button, buttons = buttons, relatedTarget = relatedTarget, region = region, ctrlKey = ctrlKey, shiftKey = shiftKey, altKey = altKey, metaKey = metaKey, modifierAltGraph = modifierAltGraph, modifierCapsLock = modifierCapsLock, modifierFn = modifierFn, modifierFnLock = modifierFnLock, modifierHyper = modifierHyper, modifierNumLock = modifierNumLock, modifierScrollLock = modifierScrollLock, modifierSuper = modifierSuper, modifierSymbol = modifierSymbol, modifierSymbolLock = modifierSymbolLock, view = view, detail = detail, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun ElementCreationOptions(param_is: String?): ElementCreationOptions = org.w3c.dom.ElementCreationOptions(param_is = param_is)

public actual fun ElementDefinitionOptions(extends_: String?): ElementDefinitionOptions = org.w3c.dom.ElementDefinitionOptions(extends_ = extends_)

public actual fun EventSourceInit(withCredentials: Boolean?): EventSourceInit = org.w3c.dom.EventSourceInit(withCredentials = withCredentials)

public actual fun GetRootNodeOptions(composed: Boolean?): GetRootNodeOptions = org.w3c.dom.GetRootNodeOptions(composed = composed)

public actual fun HashChangeEventInit(
  oldURL: String?,
  newURL: String?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): HashChangeEventInit = org.w3c.dom.HashChangeEventInit(oldURL = oldURL, newURL = newURL, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun HitRegionOptions(
  path: Path2D?,
  fillRule: CanvasFillRule?,
  id: String?,
  parentID: String?,
  cursor: String?,
  control: Element?,
  label: String?,
  role: String?,
): HitRegionOptions = org.w3c.dom.HitRegionOptions(path = path, fillRule = fillRule, id = id, parentID = parentID, cursor = cursor, control = control, label = label, role = role)

public actual fun ImageBitmapOptions(
  imageOrientation: ImageOrientation?,
  premultiplyAlpha: PremultiplyAlpha?,
  colorSpaceConversion: ColorSpaceConversion?,
  resizeWidth: Int?,
  resizeHeight: Int?,
  resizeQuality: ResizeQuality?,
): ImageBitmapOptions = org.w3c.dom.ImageBitmapOptions(imageOrientation = imageOrientation, premultiplyAlpha = premultiplyAlpha, colorSpaceConversion = colorSpaceConversion, resizeWidth = resizeWidth, resizeHeight = resizeHeight, resizeQuality = resizeQuality)

public actual fun ImageBitmapRenderingContextSettings(alpha: Boolean?): ImageBitmapRenderingContextSettings = org.w3c.dom.ImageBitmapRenderingContextSettings(alpha = alpha)

public actual fun MediaQueryListEventInit(
  media: String?,
  matches: Boolean?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): MediaQueryListEventInit = org.w3c.dom.MediaQueryListEventInit(media = media, matches = matches, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun PageTransitionEventInit(
  persisted: Boolean?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): PageTransitionEventInit = org.w3c.dom.PageTransitionEventInit(persisted = persisted, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun RelatedEventInit(
  relatedTarget: EventTarget?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): RelatedEventInit = org.w3c.dom.RelatedEventInit(relatedTarget = relatedTarget, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun ScrollOptions(behavior: ScrollBehavior?): ScrollOptions = org.w3c.dom.ScrollOptions(behavior = behavior)

public actual fun ScrollIntoViewOptions(
  block: ScrollLogicalPosition?,
  `inline`: ScrollLogicalPosition?,
  behavior: ScrollBehavior?,
): ScrollIntoViewOptions = org.w3c.dom.ScrollIntoViewOptions(block = block, inline = inline, behavior = behavior)

public actual fun ScrollToOptions(
  left: Double?,
  top: Double?,
  behavior: ScrollBehavior?,
): ScrollToOptions = org.w3c.dom.ScrollToOptions(left = left, top = top, behavior = behavior)

public actual fun ShadowRootInit(mode: ShadowRootMode?): ShadowRootInit = org.w3c.dom.ShadowRootInit(mode = mode)

public actual fun StorageEventInit(
  key: String?,
  oldValue: String?,
  newValue: String?,
  url: String?,
  storageArea: Storage?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): StorageEventInit = org.w3c.dom.StorageEventInit(key = key, oldValue = oldValue, newValue = newValue, url = url, storageArea = storageArea, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun TrackEventInit(
  track: UnionAudioTrackOrTextTrackOrVideoTrack?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): TrackEventInit = org.w3c.dom.TrackEventInit(track = track, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun WorkerOptions(type: WorkerType?, credentials: RequestCredentials?): WorkerOptions = org.w3c.dom.WorkerOptions(type = type, credentials = credentials)
