// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.fetch

import org.w3c.fetch.Request
import org.w3c.fetch.RequestCredentials
import org.w3c.fetch.RequestDestination
import org.w3c.fetch.RequestInit

public actual typealias Request = Request

public actual typealias RequestCredentials = RequestCredentials

public actual typealias RequestDestination = RequestDestination

public actual typealias RequestInit = RequestInit
