// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.mediasource

import kotlinx.browser.JsAny
import kotlinx.browser.dom.events.EventTarget

public actual abstract class SourceBuffer : EventTarget(), JsAny
