/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.webgl

import org.khronos.webgl.ArrayBuffer
import org.khronos.webgl.ArrayBufferView
import org.khronos.webgl.Float32Array
import org.khronos.webgl.Float64Array
import org.khronos.webgl.TexImageSource
import org.khronos.webgl.Uint8ClampedArray

public actual typealias ArrayBuffer = ArrayBuffer

public actual typealias ArrayBufferView = ArrayBufferView

public actual typealias Float32Array = Float32Array

public actual typealias Float64Array = Float64Array

public actual typealias Uint8ClampedArray = Uint8ClampedArray

public actual typealias TexImageSource = TexImageSource
