#!/bin/bash

cd "$(dirname "$0")"

if [[ -z "$COMPOSE_CUSTOM_VERSION" ]]; then
    echo "Must provide COMPOSE_CUSTOM_VERSION in environment" 1>&2
    exit 1
fi

pushd ../../web
./gradlew publishToMavenLocal -PCOMPOSE_CORE_VERSION="$COMPOSE_CUSTOM_VERSION" -PCOMPOSE_WEB_VERSION="$COMPOSE_CUSTOM_VERSION" || exit 1
popd

