#!/bin/bash

cd "$(dirname "$0")"
. ./prepare

pushd ..
./gradlew publishComposeJb $COMPOSE_DEFAULT_GRADLE_ARGS "$@" || exit 1
popd


. ./prepareAndroidx

pushd ..
./gradlew publishComposeJb $COMPOSE_DEFAULT_GRADLE_ARGS "$@" || exit 1
popd