#!/bin/bash

# Publish artifact without Android Layout Inspector
# Should be used is there are errors building it (on Windows, for example)
# Shouldn't be used for publishing release artifacts

cd "$(dirname "$0")"
. ./prepare

pushd ..
./gradlew publishComposeJb $COMPOSE_DEFAULT_GRADLE_ARGS -x :support:compose:ui:ui-inspection:assembleInspectorJarRelease -x :support:compose:ui:ui-inspection:dexInspectorRelease "$@" || exit 1
popd