#!/bin/bash

cd "$(dirname "$0")"
. ./prepare

pushd ..
# used in https://github.com/JetBrains/androidx/tree/jb-main/.github/workflows
./gradlew testComposeModules testComposeJbDesktop $COMPOSE_DEFAULT_GRADLE_ARGS "$@" || exit 1
popd
