/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.completion.test;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("plugins/r4a/r4a-ide/testData/completion")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class R4aCompletionTestGenerated extends AbstractR4aCompletionTest {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
    }

    public void testAllFilesPresentInCompletion() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("plugins/r4a/r4a-ide/testData/completion"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
    }

    @TestMetadata("AttributesChildrenLateInit.kt")
    public void testAttributesChildrenLateInit() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/AttributesChildrenLateInit.kt");
    }

    @TestMetadata("AttributesChildrenProperty.kt")
    public void testAttributesChildrenProperty() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/AttributesChildrenProperty.kt");
    }

    @TestMetadata("AttributesClassComponents.kt")
    public void testAttributesClassComponents() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/AttributesClassComponents.kt");
    }

    @TestMetadata("AttributesFunctionComponents.kt")
    public void testAttributesFunctionComponents() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/AttributesFunctionComponents.kt");
    }

    @TestMetadata("AttributesUsedAreOmitted.kt")
    public void testAttributesUsedAreOmitted() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/AttributesUsedAreOmitted.kt");
    }

    @TestMetadata("AttributesUsedAreOmittedFunctions.kt")
    public void testAttributesUsedAreOmittedFunctions() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/AttributesUsedAreOmittedFunctions.kt");
    }

    @TestMetadata("AttributesUsedIncludesChildren.kt")
    public void testAttributesUsedIncludesChildren() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/AttributesUsedIncludesChildren.kt");
    }

    @TestMetadata("AttributesUsedIncludesChildren2.kt")
    public void testAttributesUsedIncludesChildren2() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/AttributesUsedIncludesChildren2.kt");
    }

    @TestMetadata("NamespaceEnd.kt")
    public void testNamespaceEnd() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/NamespaceEnd.kt");
    }

    @TestMetadata("NamespaceMiddle.kt")
    public void testNamespaceMiddle() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/NamespaceMiddle.kt");
    }

    @TestMetadata("NamespaceStart.kt")
    public void testNamespaceStart() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/NamespaceStart.kt");
    }

    @TestMetadata("TagChildrenClassComponent.kt")
    public void testTagChildrenClassComponent() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/TagChildrenClassComponent.kt");
    }

    @TestMetadata("TagChildrenClassComponentWithParams.kt")
    public void testTagChildrenClassComponentWithParams() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/TagChildrenClassComponentWithParams.kt");
    }

    @TestMetadata("TagChildrenFunctionComponent.kt")
    public void testTagChildrenFunctionComponent() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/TagChildrenFunctionComponent.kt");
    }

    @TestMetadata("TagChildrenFunctionComponentWithParams.kt")
    public void testTagChildrenFunctionComponentWithParams() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/TagChildrenFunctionComponentWithParams.kt");
    }

    @TestMetadata("TagFunctionComponent.kt")
    public void testTagFunctionComponent() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/TagFunctionComponent.kt");
    }

    @TestMetadata("TagLambdaInScopeProp.kt")
    public void testTagLambdaInScopeProp() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/TagLambdaInScopeProp.kt");
    }

    @TestMetadata("TagLambdaLocalVal.kt")
    public void testTagLambdaLocalVal() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/TagLambdaLocalVal.kt");
    }

    @TestMetadata("TagLateInitChildrenClassComponent.kt")
    public void testTagLateInitChildrenClassComponent() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/TagLateInitChildrenClassComponent.kt");
    }

    @TestMetadata("TagNoChildrenClassComponent.kt")
    public void testTagNoChildrenClassComponent() throws Exception {
        runTest("plugins/r4a/r4a-ide/testData/completion/TagNoChildrenClassComponent.kt");
    }
}
