// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom

internal object EmptyNodeList : NodeList()

internal object EmptyDOMTokenList : DOMTokenList()

internal object EmptyNamedNodeMap : NamedNodeMap()

internal object EmptyHTMLCollection : HTMLCollection()

internal object EmptyDOMStringMap : DOMStringMap()

internal object EmptyTimeRanges : TimeRanges()

internal object EmptyAudioTrackList : AudioTrackList()

internal object EmptyVideoTrackList : VideoTrackList()

internal object EmptyTextTrackList : TextTrackList()

internal object EmptyCanPlayTypeResult : CanPlayTypeResult

internal object EmptyTextTrack : TextTrack()

internal object EmptyCanvasFillRule : CanvasFillRule

internal object EmptyHTMLCanvasElement : HTMLCanvasElement()

internal object EmptyImageSmoothingQuality : ImageSmoothingQuality

internal object EmptyCanvasGradient : CanvasGradient()

internal object EmptyTextMetrics : TextMetrics()

internal object EmptyImageData : ImageData()

internal object EmptyCanvasLineCap : CanvasLineCap

internal object EmptyCanvasLineJoin : CanvasLineJoin

internal object EmptyCanvasTextAlign : CanvasTextAlign

internal object EmptyCanvasTextBaseline : CanvasTextBaseline

internal object EmptyCanvasDirection : CanvasDirection

internal object EmptyNode : Node()

internal object EmptyDocumentType : DocumentType()

internal object EmptyDOMRectReadOnly : DOMRectReadOnly()

internal object EmptyDataTransferItemList : DataTransferItemList()

internal object EmptyWorkerGlobalScope : WorkerGlobalScope()

internal object EmptyWorkerLocation : WorkerLocation()

internal object EmptyWorkerNavigator : WorkerNavigator()

internal object EmptyDOMImplementation : DOMImplementation()

internal object EmptyDocumentReadyState : DocumentReadyState

internal object EmptyHTMLAllCollection : HTMLAllCollection()

internal object EmptyElement : Element()

internal object EmptyProcessingInstruction : ProcessingInstruction()

internal object EmptyAttr : Attr()

internal object EmptyNodeIterator : NodeIterator()

internal object EmptyTreeWalker : TreeWalker()

internal object EmptyWindow : Window()

internal object EmptyTouch : Touch()

internal object EmptyTouchList : TouchList()

internal object EmptyValidityState : ValidityState()

internal object EmptyUnionElementOrMouseEvent : UnionElementOrMouseEvent

internal object EmptyHTMLFormControlsCollection : HTMLFormControlsCollection()

internal object EmptySelectionMode : SelectionMode

internal object EmptyWorkerType : WorkerType

internal object EmptyHTMLOptionsCollection : HTMLOptionsCollection()

internal object EmptyHTMLTableCaptionElement : HTMLTableCaptionElement()

internal object EmptyHTMLTableSectionElement : HTMLTableSectionElement()

internal object EmptyHTMLTableRowElement : HTMLTableRowElement()

internal object EmptyScrollRestoration : ScrollRestoration

internal object EmptyMessagePort : MessagePort()

internal object EmptyPlugin : Plugin()

internal object EmptyPluginArray : PluginArray()

internal object EmptyMimeTypeArray : MimeTypeArray()

internal object EmptyShadowRootMode : ShadowRootMode

internal object EmptyApplicationCache : ApplicationCache()

internal object EmptyTextTrackKind : TextTrackKind

internal object EmptyTextTrackMode : TextTrackMode

internal object EmptyBinaryType : BinaryType

internal object EmptyLocation : Location()

internal object EmptyHistory : History()

internal object EmptyCustomElementRegistry : CustomElementRegistry()

internal object EmptyBarProp : BarProp()

internal object EmptyNavigator : Navigator()

internal object EmptyExternal : External {
  override fun AddSearchProvider() {
  }

  override fun IsSearchProviderInstalled() {
  }
}

internal object EmptyScreen : Screen()

internal object EmptyMediaQueryList : MediaQueryList()

internal object EmptyStorage : Storage()
