# Version catalog has been renamed to be imported manually with overriden 'compose' version

[versions]
compose = "1.9.0"

[libraries]
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-html-core = { module = "org.jetbrains.compose.html:html-core", version.ref = "compose" }