// Generated by the kotlinx-browser common subset generator. Do not edit.
@file:Suppress("EXPECT_ACTUAL_INCOMPATIBLE_MODALITY")

package kotlinx.browser.dom.clipboard

import kotlin.Boolean
import kotlin.Suppress
import kotlinx.browser.JsAny
import kotlinx.browser.dom.DataTransfer
import kotlinx.browser.dom.EventInit

public actual interface ClipboardEventInit : EventInit, JsAny {
  public actual var clipboardData: DataTransfer?
}

public actual interface ClipboardPermissionDescriptor : JsAny {
  public actual var allowWithoutGesture: Boolean?
}

private class JvmClipboardEventInit(
  override var clipboardData: DataTransfer?,
  override var bubbles: Boolean?,
  override var cancelable: Boolean?,
  override var composed: Boolean?,
) : ClipboardEventInit

public actual fun ClipboardEventInit(
  clipboardData: DataTransfer?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): ClipboardEventInit = JvmClipboardEventInit(clipboardData, bubbles, cancelable, composed)

private class JvmClipboardPermissionDescriptor(
  override var allowWithoutGesture: Boolean?,
) : ClipboardPermissionDescriptor

public actual fun ClipboardPermissionDescriptor(allowWithoutGesture: Boolean?): ClipboardPermissionDescriptor = JvmClipboardPermissionDescriptor(allowWithoutGesture)
