// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.clipboard

import kotlinx.browser.JsAny
import kotlinx.browser.dom.events.Event
import kotlinx.browser.dom.events.EventTarget

public actual abstract class Clipboard : EventTarget(), JsAny

public actual open class ClipboardEvent : Event(), JsAny
