// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.fetch

internal object EmptyRequestInit : RequestInit

internal object EmptyRequestDestination : RequestDestination
