// Generated by the kotlinx-browser common subset generator. Do not edit.
@file:Suppress(
  "DEFAULT_ARGUMENTS_IN_EXPECT_WITH_ACTUAL_TYPEALIAS",
  "EXPECT_ACTUAL_INCOMPATIBLE_CLASS_SCOPE",
)

package kotlinx.browser.dom.clipboard

import kotlin.Suppress
import org.w3c.dom.clipboard.Clipboard
import org.w3c.dom.clipboard.ClipboardEvent

public actual typealias Clipboard = Clipboard

public actual typealias ClipboardEvent = ClipboardEvent
