// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.clipboard

import org.w3c.dom.clipboard.Clipboard
import org.w3c.dom.clipboard.ClipboardEvent

public actual typealias Clipboard = Clipboard

public actual typealias ClipboardEvent = ClipboardEvent
