/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.webgl

import kotlinx.browser.JsAny

public actual open class ArrayBuffer : JsAny

public actual interface ArrayBufferView : JsAny

public actual open class Float32Array : ArrayBufferView, JsAny

public actual open class Float64Array : ArrayBufferView, JsAny

public actual open class Uint8ClampedArray : ArrayBufferView, JsAny

public actual interface TexImageSource
