include(":VideoPlayer:library")
include(":VideoPlayer:demo")
include(":SplitPane:library")
include(":SplitPane:demo")
include(":CodeEditor:library")
include(":CodeEditor:demo")
includeBuild("CodeEditor/platform")