// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.files

import org.w3c.files.Blob
import org.w3c.files.File
import org.w3c.files.FileList

public actual typealias Blob = Blob

public actual typealias File = File

public actual typealias FileList = FileList
