// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.webgl

import kotlinx.browser.JsAny

public expect open class ArrayBuffer : JsAny

public expect interface ArrayBufferView : JsAny

public expect open class Float32Array : ArrayBufferView, JsAny

public expect open class Float64Array : ArrayBufferView, JsAny

public expect open class Uint8ClampedArray : ArrayBufferView, JsAny

public expect interface TexImageSource
