/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.performance

import kotlinx.browser.JsAny
import kotlinx.browser.dom.events.EventTarget

public actual interface GlobalPerformance : JsAny {
  public actual val performance: Performance
}

public actual abstract class Performance : EventTarget(), JsAny
