// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.mediacapture

import kotlinx.browser.JsAny
import kotlinx.browser.dom.MediaProvider
import kotlinx.browser.dom.events.EventTarget

public actual abstract class MediaDevices : EventTarget(), JsAny

public actual open class MediaStream : EventTarget(), MediaProvider, JsAny

public actual interface MediaStreamConstraints : JsAny
