// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.mediacapture

import org.w3c.dom.mediacapture.MediaDevices
import org.w3c.dom.mediacapture.MediaStream
import org.w3c.dom.mediacapture.MediaStreamConstraints

public actual typealias MediaDevices = MediaDevices

public actual typealias MediaStream = MediaStream

public actual typealias MediaStreamConstraints = MediaStreamConstraints
