// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.mediasource

import kotlinx.browser.JsAny
import kotlinx.browser.dom.events.EventTarget

public expect abstract class SourceBuffer : EventTarget, JsAny
