// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.events

import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Suppress
import kotlinx.browser.JsAny
import kotlinx.browser.dom.EventInit
import kotlinx.browser.dom.Window

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface UIEventInit : EventInit, JsAny {
  public var view: Window?

  public var detail: Int?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface EventModifierInit : UIEventInit, JsAny {
  public var ctrlKey: Boolean?

  public var shiftKey: Boolean?

  public var altKey: Boolean?

  public var metaKey: Boolean?

  public var modifierAltGraph: Boolean?

  public var modifierCapsLock: Boolean?

  public var modifierFn: Boolean?

  public var modifierFnLock: Boolean?

  public var modifierHyper: Boolean?

  public var modifierNumLock: Boolean?

  public var modifierScrollLock: Boolean?

  public var modifierSuper: Boolean?

  public var modifierSymbol: Boolean?

  public var modifierSymbolLock: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface MouseEventInit : EventModifierInit, JsAny {
  public var screenX: Int?

  public var screenY: Int?

  public var clientX: Int?

  public var clientY: Int?

  public var button: Short?

  public var buttons: Short?

  public var relatedTarget: EventTarget?

  public var region: String?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface CompositionEventInit : UIEventInit, JsAny {
  public var `data`: String?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface FocusEventInit : UIEventInit, JsAny {
  public var relatedTarget: EventTarget?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface InputEventInit : UIEventInit, JsAny {
  public var `data`: String?

  public var isComposing: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface KeyboardEventInit : EventModifierInit, JsAny {
  public var key: String?

  public var code: String?

  public var location: Int?

  public var repeat: Boolean?

  public var isComposing: Boolean?
}

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface WheelEventInit : MouseEventInit, JsAny {
  public var deltaX: Double?

  public var deltaY: Double?

  public var deltaZ: Double?

  public var deltaMode: Int?
}

public expect fun UIEventInit(
  view: Window? = null,
  detail: Int? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): UIEventInit

public expect fun EventModifierInit(
  ctrlKey: Boolean? = null,
  shiftKey: Boolean? = null,
  altKey: Boolean? = null,
  metaKey: Boolean? = null,
  modifierAltGraph: Boolean? = null,
  modifierCapsLock: Boolean? = null,
  modifierFn: Boolean? = null,
  modifierFnLock: Boolean? = null,
  modifierHyper: Boolean? = null,
  modifierNumLock: Boolean? = null,
  modifierScrollLock: Boolean? = null,
  modifierSuper: Boolean? = null,
  modifierSymbol: Boolean? = null,
  modifierSymbolLock: Boolean? = null,
  view: Window? = null,
  detail: Int? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): EventModifierInit

public expect fun MouseEventInit(
  screenX: Int? = null,
  screenY: Int? = null,
  clientX: Int? = null,
  clientY: Int? = null,
  button: Short? = null,
  buttons: Short? = null,
  relatedTarget: EventTarget? = null,
  region: String? = null,
  ctrlKey: Boolean? = null,
  shiftKey: Boolean? = null,
  altKey: Boolean? = null,
  metaKey: Boolean? = null,
  modifierAltGraph: Boolean? = null,
  modifierCapsLock: Boolean? = null,
  modifierFn: Boolean? = null,
  modifierFnLock: Boolean? = null,
  modifierHyper: Boolean? = null,
  modifierNumLock: Boolean? = null,
  modifierScrollLock: Boolean? = null,
  modifierSuper: Boolean? = null,
  modifierSymbol: Boolean? = null,
  modifierSymbolLock: Boolean? = null,
  view: Window? = null,
  detail: Int? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): MouseEventInit

public expect fun CompositionEventInit(
  `data`: String? = null,
  view: Window? = null,
  detail: Int? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): CompositionEventInit

public expect fun FocusEventInit(
  relatedTarget: EventTarget? = null,
  view: Window? = null,
  detail: Int? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): FocusEventInit

public expect fun InputEventInit(
  `data`: String? = null,
  isComposing: Boolean? = null,
  view: Window? = null,
  detail: Int? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): InputEventInit

public expect fun KeyboardEventInit(
  key: String? = null,
  code: String? = null,
  location: Int? = null,
  repeat: Boolean? = null,
  isComposing: Boolean? = null,
  ctrlKey: Boolean? = null,
  shiftKey: Boolean? = null,
  altKey: Boolean? = null,
  metaKey: Boolean? = null,
  modifierAltGraph: Boolean? = null,
  modifierCapsLock: Boolean? = null,
  modifierFn: Boolean? = null,
  modifierFnLock: Boolean? = null,
  modifierHyper: Boolean? = null,
  modifierNumLock: Boolean? = null,
  modifierScrollLock: Boolean? = null,
  modifierSuper: Boolean? = null,
  modifierSymbol: Boolean? = null,
  modifierSymbolLock: Boolean? = null,
  view: Window? = null,
  detail: Int? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): KeyboardEventInit

public expect fun WheelEventInit(
  deltaX: Double? = null,
  deltaY: Double? = null,
  deltaZ: Double? = null,
  deltaMode: Int? = null,
  screenX: Int? = null,
  screenY: Int? = null,
  clientX: Int? = null,
  clientY: Int? = null,
  button: Short? = null,
  buttons: Short? = null,
  relatedTarget: EventTarget? = null,
  region: String? = null,
  ctrlKey: Boolean? = null,
  shiftKey: Boolean? = null,
  altKey: Boolean? = null,
  metaKey: Boolean? = null,
  modifierAltGraph: Boolean? = null,
  modifierCapsLock: Boolean? = null,
  modifierFn: Boolean? = null,
  modifierFnLock: Boolean? = null,
  modifierHyper: Boolean? = null,
  modifierNumLock: Boolean? = null,
  modifierScrollLock: Boolean? = null,
  modifierSuper: Boolean? = null,
  modifierSymbol: Boolean? = null,
  modifierSymbolLock: Boolean? = null,
  view: Window? = null,
  detail: Int? = null,
  bubbles: Boolean? = null,
  cancelable: Boolean? = null,
  composed: Boolean? = null,
): WheelEventInit
