/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.events

import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.Short
import kotlin.String
import kotlin.Unit
import kotlinx.browser.JsAny
import kotlinx.browser.JsArray
import kotlinx.browser.JsNumber
import kotlinx.browser.dom.AddEventListenerOptions
import kotlinx.browser.dom.EventInit
import kotlinx.browser.dom.EventListenerOptions
import kotlinx.browser.dom.UnionElementOrMouseEvent
import kotlinx.browser.dom.Window
import kotlinx.browser.dom.definedExternally

public expect abstract class EventTarget : JsAny {
  public fun addEventListener(
    type: String,
    callback: EventListener?,
    options: AddEventListenerOptions,
  )

  public fun addEventListener(
    type: String,
    callback: ((Event) -> Unit)?,
    options: AddEventListenerOptions,
  )

  public fun addEventListener(
    type: String,
    callback: EventListener?,
    options: Boolean,
  )

  public fun addEventListener(
    type: String,
    callback: ((Event) -> Unit)?,
    options: Boolean,
  )

  public fun addEventListener(type: String, callback: EventListener?)

  public fun addEventListener(type: String, callback: ((Event) -> Unit)?)

  public fun removeEventListener(
    type: String,
    callback: EventListener?,
    options: EventListenerOptions,
  )

  public fun removeEventListener(
    type: String,
    callback: ((Event) -> Unit)?,
    options: EventListenerOptions,
  )

  public fun removeEventListener(
    type: String,
    callback: EventListener?,
    options: Boolean,
  )

  public fun removeEventListener(
    type: String,
    callback: ((Event) -> Unit)?,
    options: Boolean,
  )

  public fun removeEventListener(type: String, callback: EventListener?)

  public fun removeEventListener(type: String, callback: ((Event) -> Unit)?)

  public fun dispatchEvent(event: Event): Boolean
}

public expect open class Event(
  type: String,
  eventInitDict: EventInit = definedExternally,
) : JsAny {
  public open val type: String

  public open val target: EventTarget?

  public open val currentTarget: EventTarget?

  public open val eventPhase: Short

  public open val bubbles: Boolean

  public open val cancelable: Boolean

  public open val defaultPrevented: Boolean

  public open val composed: Boolean

  public open val isTrusted: Boolean

  public open val timeStamp: JsNumber

  public fun composedPath(): JsArray<EventTarget>

  public fun stopPropagation()

  public fun stopImmediatePropagation()

  public fun preventDefault()

  public fun initEvent(
    type: String,
    bubbles: Boolean,
    cancelable: Boolean,
  )

  public companion object {
    public val NONE: Short

    public val CAPTURING_PHASE: Short

    public val AT_TARGET: Short

    public val BUBBLING_PHASE: Short
  }
}

public expect open class UIEvent(
  type: String,
  eventInitDict: UIEventInit = definedExternally,
) : Event,
    JsAny {
  public open val view: Window?

  public open val detail: Int

  public companion object {
    public val NONE: Short

    public val CAPTURING_PHASE: Short

    public val AT_TARGET: Short

    public val BUBBLING_PHASE: Short
  }
}

public expect open class MouseEvent(
  type: String,
  eventInitDict: MouseEventInit = definedExternally,
) : UIEvent,
    UnionElementOrMouseEvent,
    JsAny {
  public open val screenX: Int

  public open val screenY: Int

  public open val clientX: Int

  public open val clientY: Int

  public open val ctrlKey: Boolean

  public open val shiftKey: Boolean

  public open val altKey: Boolean

  public open val metaKey: Boolean

  public open val button: Short

  public open val buttons: Short

  public open val relatedTarget: EventTarget?

  public open val region: String?

  public open val pageX: Double

  public open val pageY: Double

  public open val x: Double

  public open val y: Double

  public open val offsetX: Double

  public open val offsetY: Double

  public fun getModifierState(keyArg: String): Boolean

  public companion object {
    public val NONE: Short

    public val CAPTURING_PHASE: Short

    public val AT_TARGET: Short

    public val BUBBLING_PHASE: Short
  }
}

public expect open class CompositionEvent(
  type: String,
  eventInitDict: CompositionEventInit = definedExternally,
) : UIEvent,
    JsAny {
  public open val `data`: String

  public companion object {
    public val NONE: Short

    public val CAPTURING_PHASE: Short

    public val AT_TARGET: Short

    public val BUBBLING_PHASE: Short
  }
}

public expect interface EventListener : JsAny {
  public fun handleEvent(event: Event)
}

public expect open class FocusEvent(
  type: String,
  eventInitDict: FocusEventInit = definedExternally,
) : UIEvent,
    JsAny {
  public open val relatedTarget: EventTarget?

  public companion object {
    public val NONE: Short

    public val CAPTURING_PHASE: Short

    public val AT_TARGET: Short

    public val BUBBLING_PHASE: Short
  }
}

public expect open class InputEvent(
  type: String,
  eventInitDict: InputEventInit = definedExternally,
) : UIEvent,
    JsAny {
  public open val `data`: String

  public open val isComposing: Boolean

  public companion object {
    public val NONE: Short

    public val CAPTURING_PHASE: Short

    public val AT_TARGET: Short

    public val BUBBLING_PHASE: Short
  }
}

public expect open class KeyboardEvent(
  type: String,
  eventInitDict: KeyboardEventInit = definedExternally,
) : UIEvent,
    JsAny {
  public open val key: String

  public open val code: String

  public open val location: Int

  public open val ctrlKey: Boolean

  public open val shiftKey: Boolean

  public open val altKey: Boolean

  public open val metaKey: Boolean

  public open val repeat: Boolean

  public open val isComposing: Boolean

  public open val charCode: Int

  public open val keyCode: Int

  public open val which: Int

  public fun getModifierState(keyArg: String): Boolean

  public companion object {
    public val DOM_KEY_LOCATION_STANDARD: Int

    public val DOM_KEY_LOCATION_LEFT: Int

    public val DOM_KEY_LOCATION_RIGHT: Int

    public val DOM_KEY_LOCATION_NUMPAD: Int

    public val NONE: Short

    public val CAPTURING_PHASE: Short

    public val AT_TARGET: Short

    public val BUBBLING_PHASE: Short
  }
}

public expect open class WheelEvent(
  type: String,
  eventInitDict: WheelEventInit = definedExternally,
) : MouseEvent,
    JsAny {
  public open val deltaX: Double

  public open val deltaY: Double

  public open val deltaZ: Double

  public open val deltaMode: Int

  public companion object {
    public val DOM_DELTA_PIXEL: Int

    public val DOM_DELTA_LINE: Int

    public val DOM_DELTA_PAGE: Int

    public val NONE: Short

    public val CAPTURING_PHASE: Short

    public val AT_TARGET: Short

    public val BUBBLING_PHASE: Short
  }
}
