/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
@file:Suppress(
  "ACTUAL_TYPE_ALIAS_TO_CLASS_WITH_DECLARATION_SITE_VARIANCE",
  "EXPECT_ACTUAL_INCOMPATIBLE_MODALITY",
)

package kotlinx.browser

import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.js.JsAny as BrowserJsAny
import kotlin.js.JsArray as BrowserJsArray
import kotlin.js.JsNumber as BrowserJsNumber
import kotlin.js.JsString as BrowserJsString
import kotlin.js.Promise as BrowserPromise
import kotlin.js.`get` as browserGet
import kotlin.js.`set` as browserSet
import kotlin.js.length as browserLength
import kotlin.js.toDouble as browserToDouble
import kotlin.js.toJsArray as browserToJsArray
import kotlin.js.toJsNumber as browserToJsNumber
import kotlin.js.toJsString as browserToJsString
import kotlin.js.toList as browserToList

public actual typealias JsAny = BrowserJsAny

public actual typealias JsString = BrowserJsString

public actual fun String.toJsString(): JsString = this.browserToJsString()

public actual fun JsString.toKotlinString(): String = toString()

public actual typealias JsNumber = BrowserJsNumber

public actual fun Double.toJsNumber(): JsNumber = this.browserToJsNumber()

public actual fun JsNumber.toDouble(): Double = this.browserToDouble()

public actual typealias JsDouble = BrowserJsNumber

public actual fun Double.toJsDouble(): JsDouble = this.browserToJsNumber()

public actual fun JsDouble.toKotlinDouble(): Double = this.browserToDouble()

public actual typealias JsArray<T> = BrowserJsArray<T>

public actual val JsArray<*>.length: Int
  get() = this.browserLength

public actual operator fun <T : JsAny?> JsArray<T>.`get`(index: Int): T? = this.browserGet(index)

public actual operator fun <T : JsAny?> JsArray<T>.`set`(index: Int, `value`: T) {
  this.browserSet(index, value)
}

public actual fun <T : JsAny?> JsArray<T>.toList(): List<T> = this.browserToList()

public actual fun <T : JsAny?> List<T>.toJsArray(): JsArray<T> = this.browserToJsArray()

public actual typealias Promise<T> = BrowserPromise<T>
