#Gradle
org.gradle.jvmargs=-Xmx8g

#Versions
compose.version=1.10.1

#Compose
compose.web.buildSamples=false
compose.web.tests.integration.withFirefox=true
compose.web.tests.skip.benchmarks=false
compose.html.eap.enabled=false
compose.html.eap.version=0.0.1
compose.html.eap.kotlinx-browser-common-subset.version=0.0.1+dev1

# TODO: figure out why jvmTest (web driver tests) fail with timeout with kotlin 1.9.0
integrationTestsEnabled=false
