@file:Suppress("unused", "MemberVisibilityCanBePrivate")

package org.jetbrains.compose.web.css

external interface CSSColorValue : StylePropertyValue, CSSVariableValueAs<CSSColorValue>

object Color {
    data class Named(val value: String) : CSSColorValue {
        override fun toString(): String = value
    }

    data class RGB(val r: Number, val g: Number, val b: Number) : CSSColorValue {
        override fun toString(): String = "rgb($r, $g, $b)"
    }

    data class RGBA(val r: Number, val g: Number, val b: Number, val a: Number) : CSSColorValue {
        override fun toString(): String = "rgba($r, $g, $b, $a)"
    }

    data class HSL(val h: CSSAngleValue, val s: Number, val l: Number) : CSSColorValue {
        constructor(h: Number, s: Number, l: Number) : this(h.deg, s, l)

        override fun toString(): String = "hsl($h, $s%, $l%)"
    }

    data class HSLA(val h: CSSAngleValue, val s: Number, val l: Number, val a: Number) : CSSColorValue {
        constructor(h: Number, s: Number, l: Number, a: Number) : this(h.deg, s, l, a)

        override fun toString(): String = "hsla($h, $s%, $l%, $a)"
    }

    val aliceblue = Named("aliceblue")
    val antiquewhite = Named("antiquewhite")
    val aquamarine = Named("aquamarine")
    val azure = Named("azure")
    val beige = Named("beige")
    val bisque = Named("bisque")
    val black = Named("black")
    val blanchedalmond = Named("blanchedalmond")
    val blue = Named("blue")
    val blueviolet = Named("blueviolet")
    val brown = Named("brown")
    val burlywood = Named("burlywood")
    val cadetblue = Named("cadetblue")
    val chartreuse = Named("chartreuse")
    val chocolate = Named("chocolate")
    val cornflowerblue = Named("cornflowerblue")
    val cornsilk = Named("cornsilk")
    val crimson = Named("crimson")
    val cyan = Named("cyan")
    val darkblue = Named("darkblue")
    val darkcyan = Named("darkcyan")
    val darkgoldenrod = Named("darkgoldenrod")
    val darkgray = Named("darkgray")
    val darkgreen = Named("darkgreen")
    val darkkhaki = Named("darkkhaki")
    val darkmagenta = Named("darkmagenta")
    val darkolivegreen = Named("darkolivegreen")
    val darkorange = Named("darkorange")
    val darkorchid = Named("darkorchid")
    val darkred = Named("darkred")
    val darksalmon = Named("darksalmon")
    val darkslateblue = Named("darkslateblue")
    val darkslategray = Named("darkslategray")
    val darkturquoise = Named("darkturquoise")
    val darkviolet = Named("darkviolet")
    val deeppink = Named("deeppink")
    val deepskyblue = Named("deepskyblue")
    val dimgray = Named("dimgray")
    val dodgerblue = Named("dodgerblue")
    val firebrick = Named("firebrick")
    val floralwhite = Named("floralwhite")
    val forestgreen = Named("forestgreen")
    val fuchsia = Named("fuchsia")
    val gainsboro = Named("gainsboro")
    val ghostwhite = Named("ghostwhite")
    val goldenrod = Named("goldenrod")
    val gold = Named("gold")
    val gray = Named("gray")
    val green = Named("green")
    val greenyellow = Named("greenyellow")
    val honeydew = Named("honeydew")
    val hotpink = Named("hotpink")
    val indianred = Named("indianred")
    val indigo = Named("indigo")
    val ivory = Named("ivory")
    val khaki = Named("khaki")
    val lavenderblush = Named("lavenderblush")
    val lavender = Named("lavender")
    val lawngreen = Named("lawngreen")
    val lemonchiffon = Named("lemonchiffon")
    val lightblue = Named("lightblue")
    val lightcoral = Named("lightcoral")
    val lightcyan = Named("lightcyan")
    val lightgoldenrodyellow = Named("lightgoldenrodyellow")
    val lightgray = Named("lightgray")
    val lightgreen = Named("lightgreen")
    val lightpink = Named("lightpink")
    val lightsalmon = Named("lightsalmon")
    val lightseagreen = Named("lightseagreen")
    val lightskyblue = Named("lightskyblue")
    val lightslategray = Named("lightslategray")
    val lightsteelblue = Named("lightsteelblue")
    val lightyellow = Named("lightyellow")
    val limegreen = Named("limegreen")
    val lime = Named("lime")
    val linen = Named("linen")
    val magenta = Named("magenta")
    val maroon = Named("maroon")
    val mediumaquamarine = Named("mediumaquamarine")
    val mediumblue = Named("mediumblue")
    val mediumorchid = Named("mediumorchid")
    val mediumpurple = Named("mediumpurple")
    val mediumseagreen = Named("mediumseagreen")
    val mediumslateblue = Named("mediumslateblue")
    val mediumspringgreen = Named("mediumspringgreen")
    val mediumturquoise = Named("mediumturquoise")
    val mediumvioletred = Named("mediumvioletred")
    val midnightblue = Named("midnightblue")
    val mintcream = Named("mintcream")
    val mistyrose = Named("mistyrose")
    val moccasin = Named("moccasin")
    val navajowhite = Named("navajowhite")
    val navi = Named("navi")
    val oldlace = Named("oldlace")
    val olivedrab = Named("olivedrab")
    val olive = Named("olive")
    val orange = Named("orange")
    val orangered = Named("orangered")
    val orchid = Named("orchid")
    val palegoldenrod = Named("palegoldenrod")
    val palegreen = Named("palegreen")
    val paleturquoise = Named("paleturquoise")
    val palevioletred = Named("palevioletred")
    val papayawhip = Named("papayawhip")
    val peachpuff = Named("peachpuff")
    val peru = Named("peru")
    val pink = Named("pink")
    val plum = Named("plum")
    val powderblue = Named("powderblue")
    val purple = Named("purple")
    val rebeccapurple = Named("rebeccapurple")
    val red = Named("red")
    val rosybrown = Named("rosybrown")
    val royalblue = Named("royalblue")
    val saddlebrown = Named("saddlebrown")
    val salmon = Named("salmon")
    val sandybrown = Named("sandybrown")
    val seagreen = Named("seagreen")
    val seashell = Named("seashell")
    val sienna = Named("sienna")
    val silver = Named("silver")
    val skyblue = Named("skyblue")
    val slateblue = Named("slateblue")
    val slategray = Named("slategray")
    val snow = Named("snow")
    val springgreen = Named("springgreen")
    val steelblue = Named("steelblue")
    val teal = Named("teal")
    val thistle = Named("thistle")
    val tomato = Named("tomato")
    val turquoise = Named("turquoise")
    val violet = Named("violet")
    val wheat = Named("wheat")
    val white = Named("white")
    val whitesmoke = Named("whitesmoke")
    val yellowgreen = Named("yellowgreen")
    val yellow = Named("yellow")
}

fun Color(name: String): CSSColorValue = Color.Named(name)
