// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.pointerevents

import org.w3c.dom.pointerevents.PointerEvent

public actual typealias PointerEvent = PointerEvent
