/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom

import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlinx.browser.JsAny
import kotlinx.browser.JsArray
import kotlinx.browser.JsString
import kotlinx.browser.Promise
import org.w3c.dom.`get` as browserGet

public actual operator fun Window.`get`(name: String): JsAny? = this.browserGet(name)

public actual operator fun Document.`get`(name: String): JsAny? = this.browserGet(name)

public actual fun BoxQuadOptions(box: CSSBoxType?, relativeTo: JsAny?): BoxQuadOptions = org.w3c.dom.BoxQuadOptions(box = box, relativeTo = relativeTo)

public actual fun CustomEventInit(
  detail: JsAny?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): CustomEventInit = org.w3c.dom.CustomEventInit(detail = detail, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun ErrorEventInit(
  message: String?,
  filename: String?,
  lineno: Int?,
  colno: Int?,
  error: JsAny?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): ErrorEventInit = org.w3c.dom.ErrorEventInit(message = message, filename = filename, lineno = lineno, colno = colno, error = error, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun MessageEventInit(
  `data`: JsAny?,
  origin: String?,
  lastEventId: String?,
  source: UnionMessagePortOrWindowProxy?,
  ports: JsArray<MessagePort>?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): MessageEventInit = org.w3c.dom.MessageEventInit(data = data, origin = origin, lastEventId = lastEventId, source = source, ports = ports, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun MutationObserverInit(
  childList: Boolean?,
  attributes: Boolean?,
  characterData: Boolean?,
  subtree: Boolean?,
  attributeOldValue: Boolean?,
  characterDataOldValue: Boolean?,
  attributeFilter: JsArray<JsString>?,
): MutationObserverInit = org.w3c.dom.MutationObserverInit(childList = childList, attributes = attributes, characterData = characterData, subtree = subtree, attributeOldValue = attributeOldValue, characterDataOldValue = characterDataOldValue, attributeFilter = attributeFilter)

public actual fun PopStateEventInit(
  state: JsAny?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): PopStateEventInit = org.w3c.dom.PopStateEventInit(state = state, bubbles = bubbles, cancelable = cancelable, composed = composed)

public actual fun PromiseRejectionEventInit(
  promise: Promise<*>?,
  reason: JsAny?,
  bubbles: Boolean?,
  cancelable: Boolean?,
  composed: Boolean?,
): PromiseRejectionEventInit = org.w3c.dom.PromiseRejectionEventInit(promise = promise, reason = reason, bubbles = bubbles, cancelable = cancelable, composed = composed)
