/*
 * Copyright 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.compose.ui.input.key

// TODO(demin): implement most of key codes

/**
 * Actual implementation of [Key] for Desktop.
 *
 * @param keyCode an integer code representing the key pressed.
 */
actual inline class Key(val keyCode: Int) {
    actual companion object {
        actual val Unknown = Key(0)
        actual val SoftLeft = Key(0)
        actual val SoftRight = Key(0)
        actual val Home = Key(0)
        actual val Back = Key(0)
        actual val Help = Key(0)
        actual val NavigatePrevious = Key(0)
        actual val NavigateNext = Key(0)
        actual val NavigateIn = Key(0)
        actual val NavigateOut = Key(0)
        actual val SystemNavigationUp = Key(0)
        actual val SystemNavigationDown = Key(0)
        actual val SystemNavigationLeft = Key(0)
        actual val SystemNavigationRight = Key(0)
        actual val Call = Key(0)
        actual val EndCall = Key(0)
        actual val DPadUp = Key(0)
        actual val DPadDown = Key(0)
        actual val DPadLeft = Key(0)
        actual val DPadRight = Key(0)
        actual val DPadCenter = Key(0)
        actual val DPadUpLeft = Key(0)
        actual val DPadDownLeft = Key(0)
        actual val DPadUpRight = Key(0)
        actual val DPadDownRight = Key(0)
        actual val VolumeUp = Key(0)
        actual val VolumeDown = Key(0)
        actual val Power = Key(0)
        actual val Camera = Key(0)
        actual val Clear = Key(0)
        actual val Number0 = Key(0)
        actual val Number1 = Key(0)
        actual val Number2 = Key(0)
        actual val Number3 = Key(0)
        actual val Number4 = Key(0)
        actual val Number5 = Key(0)
        actual val Number6 = Key(0)
        actual val Number7 = Key(0)
        actual val Number8 = Key(0)
        actual val Number9 = Key(0)
        actual val Number11 = Key(0)
        actual val Number12 = Key(0)
        actual val Plus = Key(0)
        actual val Minus = Key(0)
        actual val Multiply = Key(0)
        actual val Equals = Key(0)
        actual val Pound = Key(0)
        actual val A = Key(0)
        actual val B = Key(0)
        actual val C = Key(0)
        actual val D = Key(0)
        actual val E = Key(0)
        actual val F = Key(0)
        actual val G = Key(0)
        actual val H = Key(0)
        actual val I = Key(0)
        actual val J = Key(0)
        actual val K = Key(0)
        actual val L = Key(0)
        actual val M = Key(0)
        actual val N = Key(0)
        actual val O = Key(0)
        actual val P = Key(0)
        actual val Q = Key(0)
        actual val R = Key(0)
        actual val S = Key(0)
        actual val T = Key(0)
        actual val U = Key(0)
        actual val V = Key(0)
        actual val W = Key(0)
        actual val X = Key(0)
        actual val Y = Key(0)
        actual val Z = Key(0)
        actual val Comma = Key(0)
        actual val Period = Key(0)
        actual val AltLeft = Key(0)
        actual val AltRight = Key(0)
        actual val ShiftLeft = Key(0)
        actual val ShiftRight = Key(0)
        actual val Tab = Key(0)
        actual val Spacebar = Key(0)
        actual val Symbol = Key(0)
        actual val Browser = Key(0)
        actual val Envelope = Key(0)
        actual val Enter = Key(0)
        actual val Backspace = Key(0)
        actual val Delete = Key(0)
        actual val Escape = Key(0)
        actual val CtrlLeft = Key(0)
        actual val CtrlRight = Key(0)
        actual val CapsLock = Key(0)
        actual val ScrollLock = Key(0)
        actual val MetaLeft = Key(0)
        actual val MetaRight = Key(0)
        actual val Function = Key(0)
        actual val PrintScreen = Key(0)
        actual val Break = Key(0)
        actual val MoveHome = Key(0)
        actual val MoveEnd = Key(0)
        actual val Insert = Key(0)
        actual val Cut = Key(0)
        actual val Copy = Key(0)
        actual val Paste = Key(0)
        actual val Grave = Key(0)
        actual val LeftBracket = Key(0)
        actual val RightBracket = Key(0)
        actual val Slash = Key(0)
        actual val Backslash = Key(0)
        actual val Semicolon = Key(0)
        actual val Apostrophe = Key(0)
        actual val At = Key(0)
        actual val Number = Key(0)
        actual val HeadsetHook = Key(0)
        actual val Focus = Key(0)
        actual val Menu = Key(0)
        actual val Notification = Key(0)
        actual val Search = Key(0)
        actual val PageUp = Key(0)
        actual val PageDown = Key(0)
        actual val PictureSymbols = Key(0)
        actual val SwitchCharset = Key(0)
        actual val ButtonA = Key(0)
        actual val ButtonB = Key(0)
        actual val ButtonC = Key(0)
        actual val ButtonX = Key(0)
        actual val ButtonY = Key(0)
        actual val ButtonZ = Key(0)
        actual val ButtonL1 = Key(0)
        actual val ButtonR1 = Key(0)
        actual val ButtonL2 = Key(0)
        actual val ButtonR2 = Key(0)
        actual val ButtonThumbLeft = Key(0)
        actual val ButtonThumbRight = Key(0)
        actual val ButtonStart = Key(0)
        actual val ButtonSelect = Key(0)
        actual val ButtonMode = Key(0)
        actual val Button1 = Key(0)
        actual val Button2 = Key(0)
        actual val Button3 = Key(0)
        actual val Button4 = Key(0)
        actual val Button5 = Key(0)
        actual val Button6 = Key(0)
        actual val Button7 = Key(0)
        actual val Button8 = Key(0)
        actual val Button9 = Key(0)
        actual val Button10 = Key(0)
        actual val Button11 = Key(0)
        actual val Button12 = Key(0)
        actual val Button13 = Key(0)
        actual val Button14 = Key(0)
        actual val Button15 = Key(0)
        actual val Button16 = Key(0)
        actual val Forward = Key(0)
        actual val F1 = Key(0)
        actual val F2 = Key(0)
        actual val F3 = Key(0)
        actual val F4 = Key(0)
        actual val F5 = Key(0)
        actual val F6 = Key(0)
        actual val F7 = Key(0)
        actual val F8 = Key(0)
        actual val F9 = Key(0)
        actual val F10 = Key(0)
        actual val F11 = Key(0)
        actual val F12 = Key(0)
        actual val NumLock = Key(0)
        actual val NumPad0 = Key(0)
        actual val NumPad1 = Key(0)
        actual val NumPad2 = Key(0)
        actual val NumPad3 = Key(0)
        actual val NumPad4 = Key(0)
        actual val NumPad5 = Key(0)
        actual val NumPad6 = Key(0)
        actual val NumPad7 = Key(0)
        actual val NumPad8 = Key(0)
        actual val NumPad9 = Key(0)
        actual val NumPadDivide = Key(0)
        actual val NumPadMultiply = Key(0)
        actual val NumPadSubtract = Key(0)
        actual val NumPadAdd = Key(0)
        actual val NumPadDot = Key(0)
        actual val NumPadComma = Key(0)
        actual val NumPadEnter = Key(0)
        actual val NumPadEquals = Key(0)
        actual val NumPadLeftParenthesis = Key(0)
        actual val NumPadRightParenthesis = Key(0)
        actual val MediaPlay = Key(0)
        actual val MediaPause = Key(0)
        actual val MediaPlayPause = Key(0)
        actual val MediaStop = Key(0)
        actual val MediaRecord = Key(0)
        actual val MediaNext = Key(0)
        actual val MediaPrevious = Key(0)
        actual val MediaRewind = Key(0)
        actual val MediaFastForward = Key(0)
        actual val MediaClose = Key(0)
        actual val MediaAudioTrack = Key(0)
        actual val MediaEject = Key(0)
        actual val MediaTopMenu = Key(0)
        actual val MediaSkipForward = Key(0)
        actual val MediaSkipBackward = Key(0)
        actual val MediaStepForward = Key(0)
        actual val MediaStepBackward = Key(0)
        actual val MicrophoneMute = Key(0)
        actual val VolumeMute = Key(0)
        actual val Info = Key(0)
        actual val ChannelUp = Key(0)
        actual val ChannelDown = Key(0)
        actual val ZoomIn = Key(0)
        actual val ZoomOut = Key(0)
        actual val Tv = Key(0)
        actual val Window = Key(0)
        actual val Guide = Key(0)
        actual val Dvr = Key(0)
        actual val Bookmark = Key(0)
        actual val Captions = Key(0)
        actual val Settings = Key(0)
        actual val TvPower = Key(0)
        actual val TvInput = Key(0)
        actual val SetTopBoxPower = Key(0)
        actual val SetTopBoxInput = Key(0)
        actual val AvReceiverPower = Key(0)
        actual val AvReceiverInput = Key(0)
        actual val ProgramRed = Key(0)
        actual val ProgramGreen = Key(0)
        actual val ProgramYellow = Key(0)
        actual val ProgramBlue = Key(0)
        actual val AppSwitch = Key(0)
        actual val LanguageSwitch = Key(0)
        actual val MannerMode = Key(0)
        actual val Toggle2D3D = Key(0)
        actual val Contacts = Key(0)
        actual val Calendar = Key(0)
        actual val Music = Key(0)
        actual val Calculator = Key(0)
        actual val ZenkakuHankaru = Key(0)
        actual val Eisu = Key(0)
        actual val Muhenkan = Key(0)
        actual val Henkan = Key(0)
        actual val KatakanaHiragana = Key(0)
        actual val Yen = Key(0)
        actual val Ro = Key(0)
        actual val Kana = Key(0)
        actual val Assist = Key(0)
        actual val BrightnessDown = Key(0)
        actual val BrightnessUp = Key(0)
        actual val Sleep = Key(0)
        actual val WakeUp = Key(0)
        actual val SoftSleep = Key(0)
        actual val Pairing = Key(0)
        actual val LastChannel = Key(0)
        actual val TvDataService = Key(0)
        actual val VoiceAssist = Key(0)
        actual val TvRadioService = Key(0)
        actual val TvTeletext = Key(0)
        actual val TvNumberEntry = Key(0)
        actual val TvTerrestrialAnalog = Key(0)
        actual val TvTerrestrialDigital = Key(0)
        actual val TvSatellite = Key(0)
        actual val TvSatelliteBs = Key(0)
        actual val TvSatelliteCs = Key(0)
        actual val TvSatelliteService = Key(0)
        actual val TvNetwork = Key(0)
        actual val TvAntennaCable = Key(0)
        actual val TvInputHdmi1 = Key(0)
        actual val TvInputHdmi2 = Key(0)
        actual val TvInputHdmi3 = Key(0)
        actual val TvInputHdmi4 = Key(0)
        actual val TvInputComposite1 = Key(0)
        actual val TvInputComposite2 = Key(0)
        actual val TvInputComponent1 = Key(0)
        actual val TvInputComponent2 = Key(0)
        actual val TvInputVga1 = Key(0)
        actual val TvAudioDescription = Key(0)
        actual val TvAudioDescriptionMixingVolumeUp = Key(0)
        actual val TvAudioDescriptionMixingVolumeDown = Key(0)
        actual val TvZoomMode = Key(0)
        actual val TvContentsMenu = Key(0)
        actual val TvMediaContextMenu = Key(0)
        actual val TvTimerProgramming = Key(0)
        actual val StemPrimary = Key(0)
        actual val Stem1 = Key(0)
        actual val Stem2 = Key(0)
        actual val Stem3 = Key(0)
        actual val AllApps = Key(0)
        actual val Refresh = Key(0)
        actual val ThumbsUp = Key(0)
        actual val ThumbsDown = Key(0)
        actual val ProfileSwitch = Key(0)
    }

    actual override fun toString(): String {
        return "Key code: $keyCode"
    }
}
