// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.files

import kotlinx.browser.JsAny
import kotlinx.browser.dom.ImageBitmapSource
import kotlinx.browser.dom.MediaProvider

public expect open class Blob : MediaProvider, ImageBitmapSource, JsAny

public expect open class File : Blob, JsAny

public expect abstract class FileList : JsAny
