/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.encryptedmedia

import kotlinx.browser.JsAny

public actual interface MediaKeySystemConfiguration : JsAny

public actual abstract class MediaKeys : JsAny
