/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.svg

import kotlin.Int
import kotlinx.browser.JsAny
import org.w3c.dom.svg.`get` as browserGet
import org.w3c.dom.svg.`set` as browserSet

public actual operator fun SVGNameList.`get`(index: Int): JsAny? = this.browserGet(index)

public actual operator fun SVGNameList.`set`(index: Int, newItem: JsAny?) {
  this.browserSet(index, newItem)
}
