/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.css.masking

import kotlin.Short
import kotlinx.browser.JsAny
import kotlinx.browser.dom.svg.SVGAnimatedEnumeration
import kotlinx.browser.dom.svg.SVGAnimatedLength
import kotlinx.browser.dom.svg.SVGAnimatedTransformList
import kotlinx.browser.dom.svg.SVGElement
import kotlinx.browser.dom.svg.SVGUnitTypes

public expect abstract class SVGClipPathElement : SVGElement, SVGUnitTypes, JsAny {
  public open val clipPathUnits: SVGAnimatedEnumeration

  public open val transform: SVGAnimatedTransformList

  public companion object {
    public val SVG_UNIT_TYPE_UNKNOWN: Short

    public val SVG_UNIT_TYPE_USERSPACEONUSE: Short

    public val SVG_UNIT_TYPE_OBJECTBOUNDINGBOX: Short

    public val ELEMENT_NODE: Short

    public val ATTRIBUTE_NODE: Short

    public val TEXT_NODE: Short

    public val CDATA_SECTION_NODE: Short

    public val ENTITY_REFERENCE_NODE: Short

    public val ENTITY_NODE: Short

    public val PROCESSING_INSTRUCTION_NODE: Short

    public val COMMENT_NODE: Short

    public val DOCUMENT_NODE: Short

    public val DOCUMENT_TYPE_NODE: Short

    public val DOCUMENT_FRAGMENT_NODE: Short

    public val NOTATION_NODE: Short

    public val DOCUMENT_POSITION_DISCONNECTED: Short

    public val DOCUMENT_POSITION_PRECEDING: Short

    public val DOCUMENT_POSITION_FOLLOWING: Short

    public val DOCUMENT_POSITION_CONTAINS: Short

    public val DOCUMENT_POSITION_CONTAINED_BY: Short

    public val DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: Short
  }
}

public expect abstract class SVGMaskElement : SVGElement, SVGUnitTypes, JsAny {
  public open val maskUnits: SVGAnimatedEnumeration

  public open val maskContentUnits: SVGAnimatedEnumeration

  public open val x: SVGAnimatedLength

  public open val y: SVGAnimatedLength

  public open val width: SVGAnimatedLength

  public open val height: SVGAnimatedLength

  public companion object {
    public val SVG_UNIT_TYPE_UNKNOWN: Short

    public val SVG_UNIT_TYPE_USERSPACEONUSE: Short

    public val SVG_UNIT_TYPE_OBJECTBOUNDINGBOX: Short

    public val ELEMENT_NODE: Short

    public val ATTRIBUTE_NODE: Short

    public val TEXT_NODE: Short

    public val CDATA_SECTION_NODE: Short

    public val ENTITY_REFERENCE_NODE: Short

    public val ENTITY_NODE: Short

    public val PROCESSING_INSTRUCTION_NODE: Short

    public val COMMENT_NODE: Short

    public val DOCUMENT_NODE: Short

    public val DOCUMENT_TYPE_NODE: Short

    public val DOCUMENT_FRAGMENT_NODE: Short

    public val NOTATION_NODE: Short

    public val DOCUMENT_POSITION_DISCONNECTED: Short

    public val DOCUMENT_POSITION_PRECEDING: Short

    public val DOCUMENT_POSITION_FOLLOWING: Short

    public val DOCUMENT_POSITION_CONTAINS: Short

    public val DOCUMENT_POSITION_CONTAINED_BY: Short

    public val DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: Short
  }
}
