// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.performance

import kotlinx.browser.JsAny
import kotlinx.browser.dom.events.EventTarget

public expect interface GlobalPerformance : JsAny {
  public val performance: Performance
}

public expect abstract class Performance : EventTarget, JsAny
