/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
@file:Suppress("EXPECT_ACTUAL_INCOMPATIBLE_CLASS_SCOPE")

package kotlinx.browser.dom.svg

import kotlin.Boolean
import kotlin.Suppress

public actual typealias SVGBoundingBoxOptions = org.w3c.dom.svg.SVGBoundingBoxOptions

public actual fun SVGBoundingBoxOptions(
  fill: Boolean?,
  stroke: Boolean?,
  markers: Boolean?,
  clipped: Boolean?,
): SVGBoundingBoxOptions = org.w3c.dom.svg.SVGBoundingBoxOptions(fill = fill, stroke = stroke, markers = markers, clipped = clipped)
