/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.fetch

import kotlinx.browser.JsAny

public expect open class Request : JsAny

public expect interface RequestCredentials : JsAny

public expect interface RequestDestination : JsAny

public expect interface RequestInit : JsAny
