[versions]
kotlin = "1.9.0"

[libraries]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-sdk = "org.jetbrains.intellij:1.15.0"
intellij-changelog = "org.jetbrains.changelog:2.2.0"
