[versions]
kotlin = "1.9.23"
ideaPlugin = "2.1.0"
idea = "2024.2.1"
changelog = "2.2.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-plugin = { id = "org.jetbrains.intellij.platform", version.ref = "ideaPlugin" }
intellij-changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
