[versions]
kotlin = "2.1.21"
ideaPlugin = "2.9.0"
idea = "2025.2.2"
changelog = "2.2.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-plugin = { id = "org.jetbrains.intellij.platform", version.ref = "ideaPlugin" }
intellij-changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
