// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.workers

import kotlinx.browser.JsAny
import kotlinx.browser.dom.events.EventTarget

public expect interface UnionMessagePortOrServiceWorker

public expect interface UnionClientOrMessagePortOrServiceWorker

public expect abstract class CacheStorage : JsAny

public expect abstract class ServiceWorkerContainer : EventTarget, JsAny
