kotlin.code.style=official
xcodeproj=iosApp
android.useAndroidX=true
org.gradle.jvmargs=-Xmx8g

org.gradle.configuration-cache=true
org.gradle.caching=true
org.jetbrains.compose.experimental.jscanvas.enabled=true
org.jetbrains.compose.experimental.macos.enabled=true
kotlin.version=2.4.10
agp.version=9.1.1
compose.version=1.12.0
