// Generated by the kotlinx-browser common subset generator. Do not edit.
@file:Suppress("EXPECT_ACTUAL_INCOMPATIBLE_MODALITY")

package kotlinx.browser.dom.svg

import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlinx.browser.JsAny
import kotlinx.browser.dom.BeforeUnloadEvent
import kotlinx.browser.dom.HashChangeEvent
import kotlinx.browser.dom.MessageEvent
import kotlinx.browser.dom.PageTransitionEvent
import kotlinx.browser.dom.PopStateEvent
import kotlinx.browser.dom.PromiseRejectionEvent
import kotlinx.browser.dom.StorageEvent
import kotlinx.browser.dom.WindowEventHandlers
import kotlinx.browser.dom.events.Event

public actual abstract class SVGSVGElement : WindowEventHandlers, JsAny {
  override var onafterprint: ((Event) -> Unit)? = null

  override var onbeforeprint: ((Event) -> Unit)? = null

  override var onbeforeunload: ((BeforeUnloadEvent) -> String?)? = null

  override var onhashchange: ((HashChangeEvent) -> Unit)? = null

  override var onlanguagechange: ((Event) -> Unit)? = null

  override var onmessage: ((MessageEvent) -> Unit)? = null

  override var onoffline: ((Event) -> Unit)? = null

  override var ononline: ((Event) -> Unit)? = null

  override var onpagehide: ((PageTransitionEvent) -> Unit)? = null

  override var onpageshow: ((PageTransitionEvent) -> Unit)? = null

  override var onpopstate: ((PopStateEvent) -> Unit)? = null

  override var onrejectionhandled: ((Event) -> Unit)? = null

  override var onstorage: ((StorageEvent) -> Unit)? = null

  override var onunhandledrejection: ((PromiseRejectionEvent) -> Unit)? = null

  override var onunload: ((Event) -> Unit)? = null
}
