// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.svg

import kotlinx.browser.JsAny
import kotlinx.browser.dom.WindowEventHandlers

public expect abstract class SVGSVGElement : WindowEventHandlers, JsAny
