/*
 * Copyright 2026 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

// Generated by the kotlinx-browser common subset generator. Do not edit.
package kotlinx.browser.dom.svg

import kotlin.Boolean
import kotlin.Suppress
import kotlinx.browser.JsAny

@Suppress("EXPECT_ACTUAL_IR_INCOMPATIBILITY")
public expect interface SVGBoundingBoxOptions : JsAny {
  public var fill: Boolean?

  public var stroke: Boolean?

  public var markers: Boolean?

  public var clipped: Boolean?
}

public expect fun SVGBoundingBoxOptions(
  fill: Boolean? = null,
  stroke: Boolean? = null,
  markers: Boolean? = null,
  clipped: Boolean? = null,
): SVGBoundingBoxOptions
